name: flutter_mobile_simple
description: Minimal mobile Form Concierge example without local persistence or app localization.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  form_concierge_client:
    path: ../../client
  form_concierge:
    path: ../../widget
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
