/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerEnv src/worker-env.d.ts` (hash: 9deb244c23604be21ad2148e38d58835)
interface __BaseEnv_WorkerEnv {
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	LOGIN_RATE_LIMITER: RateLimit;
	ANON_CREATE_RATE_LIMITER: RateLimit;
	PUBLIC_BASE_URL: string;
	PUBLIC_FORM_ASSET_BASE_URL: string;
	TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
