/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=/Users/me/Projects/form_concierge/worker/.wrangler.check.jsonc --include-runtime=false --strict-vars=false --env-interface=WorkerEnv /Users/me/Projects/form_concierge/worker/src/worker-env.d.ts` (hash: 421cbc709cab2f1becbb3a074c534c64)
interface __BaseEnv_WorkerEnv {
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	GEMINI_API_KEY: SecretsStoreSecret;
	OPENAI_API_KEY: SecretsStoreSecret;
	CLAUDE_API_KEY: SecretsStoreSecret;
	GROQ_API_KEY: SecretsStoreSecret;
	CEREBRAS_API_KEY: SecretsStoreSecret;
	SMTP_PASSWORD: SecretsStoreSecret;
	TURNSTILE_SITE_KEY: SecretsStoreSecret;
	TURNSTILE_SECRET_KEY: SecretsStoreSecret;
	LOGIN_RATE_LIMITER: RateLimit;
	ANON_CREATE_RATE_LIMITER: RateLimit;
	PUBLIC_WRITE_RATE_LIMITER: RateLimit;
	PUBLIC_BASE_URL: string;
	PUBLIC_FORM_ASSET_BASE_URL: string;
	CF_ACCOUNT_ID: string;
	CF_SECRETS_STORE_ID: string;
	QUOTA_RESPONSES_PER_ACCOUNT_DAY: string;
	QUOTA_RESPONSES_PER_IP_DAY: string;
	QUOTA_RESPONSES_PER_SURVEY_DAY: string;
	QUOTA_UPLOAD_BYTES_PER_ACCOUNT_DAY: string;
	QUOTA_STORED_BYTES_PER_ACCOUNT: string;
	QUOTA_AI_GENERATIONS_PER_ACCOUNT_DAY: string;
	QUOTA_AI_GENERATIONS_PER_SURVEY_DAY: string;
	QUOTA_EMAILS_PER_SURVEY_DAY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
