/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerEnv src/worker-env.d.ts` (hash: 8095978502cb0fcca1dddbf7715acd12)
interface __BaseEnv_WorkerEnv {
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	GEMINI_API_KEY: SecretsStoreSecret;
	OPENAI_API_KEY: SecretsStoreSecret;
	CLAUDE_API_KEY: SecretsStoreSecret;
	CEREBRAS_API_KEY: SecretsStoreSecret;
	SMTP_PASSWORD: SecretsStoreSecret;
	TURNSTILE_SITE_KEY: SecretsStoreSecret;
	TURNSTILE_SECRET_KEY: SecretsStoreSecret;
	LOGIN_RATE_LIMITER: RateLimit;
	ANON_CREATE_RATE_LIMITER: RateLimit;
	PUBLIC_BASE_URL: string;
	PUBLIC_FORM_ASSET_BASE_URL: string;
	CF_ACCOUNT_ID: string;
	CF_SECRETS_STORE_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
