import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('ja'),
    Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'),
    Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'),
    Locale('ko'),
    Locale('de'),
  ];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String text(String key, [Map<String, Object?> values = const {}]) {
    final localeKey = _localeKey(locale);
    var result =
        _localizedValues[localeKey]?[key] ??
        _localizedValues['en']?[key] ??
        key;
    for (final entry in values.entries) {
      result = result.replaceAll(
        '{${entry.key}}',
        entry.value?.toString() ?? '',
      );
    }
    return result;
  }

  String message(String value) {
    for (final prefix in _errorPrefixes) {
      if (value.startsWith(prefix)) {
        return text(prefix, {'error': value.substring(prefix.length)});
      }
    }
    return text(value);
  }

  static Locale? localeResolutionCallback(
    Locale? locale,
    Iterable<Locale> supportedLocales,
  ) {
    if (locale == null) return const Locale('en');
    if (locale.languageCode == 'zh') {
      final country = locale.countryCode?.toUpperCase();
      final script = locale.scriptCode;
      if (script == 'Hant' ||
          country == 'TW' ||
          country == 'HK' ||
          country == 'MO') {
        return const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant');
      }
      return const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans');
    }
    for (final supported in supportedLocales) {
      if (supported.languageCode == locale.languageCode) return supported;
    }
    return const Locale('en');
  }

  static String _localeKey(Locale locale) {
    if (locale.languageCode == 'zh') {
      return locale.scriptCode == 'Hant' ? 'zh_Hant' : 'zh_Hans';
    }
    return locale.languageCode;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    if (locale.languageCode == 'zh') return true;
    return AppLocalizations.supportedLocales.any(
      (supported) => supported.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsBuildContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);

  String tr(String key, [Map<String, Object?> values = const {}]) {
    return l10n.text(key, values);
  }

  String trMessage(String value) {
    return l10n.message(value);
  }
}

const _errorPrefixes = [
  'Registration failed: ',
  'Failed to load config: ',
  'Failed to load surveys: ',
  'Failed to load projects: ',
  'Failed to load project: ',
  'Failed to create project: ',
  'Failed to update project: ',
  'Failed to delete project: ',
  'Failed to delete survey: ',
  'Failed to publish survey: ',
  'Failed to close survey: ',
  'Failed to reopen survey: ',
  'Failed to update web publication: ',
  'Failed to load survey: ',
  'Failed to load questions: ',
  'Failed to create question: ',
  'Failed to update question: ',
  'Failed to delete question: ',
  'Failed to reorder questions: ',
  'Failed to create choice: ',
  'Failed to update choice: ',
  'Failed to delete choice: ',
  'Failed to save visibility rules: ',
  'Failed to create survey: ',
  'Failed to update survey: ',
  'Failed to generate questions: ',
  'Failed to load results: ',
  'Failed to load responses: ',
  'Failed to export responses: ',
  'Failed to delete response: ',
  'Failed to send reply: ',
  'Failed to load notification settings: ',
  'Failed to load settings: ',
  'Failed to save settings: ',
  'Failed to toggle notifications: ',
  'Failed to send test notification: ',
  'Failed to load users: ',
  'Failed to create user: ',
  'Failed to update role: ',
  'Failed to delete user: ',
  'Failed to update user: ',
];

const _localizedValues = <String, Map<String, String>>{
  'en': {
    'Form Concierge Admin': 'Form Concierge Admin',
    'Form Concierge': 'Form Concierge',
    'Admin Dashboard': 'Admin Dashboard',
    'Welcome! Create your admin account to get started.':
        'Welcome! Create your admin account to get started.',
    'Email': 'Email',
    'Password': 'Password',
    'Forgot Password?': 'Forgot Password?',
    'Create Account': 'Create Account',
    'Login': 'Login',
    'Forgot Password': 'Forgot Password',
    'Reset Your Password': 'Reset Your Password',
    "Enter your email address and we'll send you a verification code.":
        "Enter your email address and we'll send you a verification code.",
    'Send Code': 'Send Code',
    'Back to Login': 'Back to Login',
    'Verify Code': 'Verify Code',
    'Check Your Email': 'Check Your Email',
    'We sent a verification code to:': 'We sent a verification code to:',
    'Verification Code': 'Verification Code',
    'Enter 6-digit code': 'Enter 6-digit code',
    'Verify': 'Verify',
    'Cancel': 'Cancel',
    'Password Reset Complete': 'Password Reset Complete',
    'Your password has been successfully reset. You can now login with your new password.':
        'Your password has been successfully reset. You can now login with your new password.',
    'Go to Login': 'Go to Login',
    'New Password': 'New Password',
    'Create New Password': 'Create New Password',
    'Enter a new password for your account.':
        'Enter a new password for your account.',
    'Confirm Password': 'Confirm Password',
    'Reset Password': 'Reset Password',
    'Please enter a password': 'Please enter a password',
    'Password must be at least 8 characters':
        'Password must be at least 8 characters',
    'Passwords do not match': 'Passwords do not match',
    'Surveys': 'Surveys',
    'Refresh': 'Refresh',
    'User Management': 'User Management',
    'Settings': 'Settings',
    'Logout': 'Logout',
    'New Survey': 'New Survey',
    'Retry': 'Retry',
    'No surveys yet': 'No surveys yet',
    'Create your first survey to get started':
        'Create your first survey to get started',
    'Create Survey': 'Create Survey',
    'Web public': 'Web public',
    'New Project': 'New Project',
    'Project Settings': 'Project Settings',
    'Project not found': 'Project not found',
    'Create Project': 'Create Project',
    'Project URL Slug': 'Project URL Slug',
    'Use a dedicated host to open this project without a slug.':
        'Use a dedicated host to open this project without a slug.',
    'Localized project names': 'Localized project names',
    'Project name': 'Project name',
    'Enter project name': 'Enter project name',
    'Project name is required': 'Project name is required',
    'Brief description of the project': 'Brief description of the project',
    'Delete Survey': 'Delete Survey',
    'Delete survey confirmation':
        'Are you sure you want to delete "{title}"?\n\nThis will also delete all questions and responses. This action cannot be undone.',
    'Publish': 'Publish',
    'Close': 'Close',
    'Reopen': 'Reopen',
    'View Responses': 'View Responses',
    'Delete': 'Delete',
    'Draft': 'Draft',
    'Published': 'Published',
    'Closed': 'Closed',
    'Archived': 'Archived',
    'Responses': 'Responses',
    'Export responses': 'Export responses',
    'Export CSV': 'Export CSV',
    'Export JSON': 'Export JSON',
    'Results': 'Results',
    'Individual': 'Individual',
    'Notifications': 'Notifications',
    'Delete Response': 'Delete Response',
    'Delete response confirmation':
        'Are you sure you want to delete this response?\n\nThis action cannot be undone.',
    'Reply to respondent': 'Reply to respondent',
    'Message': 'Message',
    'Send': 'Send',
    'Reply sent': 'Reply sent',
    'Exported {filename}': 'Exported {filename}',
    'No responses yet': 'No responses yet',
    'Share your survey to start collecting responses':
        'Share your survey to start collecting responses',
    'Total Responses': 'Total Responses',
    'Results by Question': 'Results by Question',
    'Choice': 'Choice',
    'Count': 'Count',
    'No text responses': 'No text responses',
    '{count} response': '{count} response',
    '{count} responses': '{count} responses',
    '... and {count} more responses': '... and {count} more responses',
    'Previous page': 'Previous page',
    'Next page': 'Next page',
    'Page {currentPage} of {totalPages}': 'Page {currentPage} of {totalPages}',
    'User #{id}': 'User #{id}',
    'Anonymous': 'Anonymous',
    'Reply': 'Reply',
    'Delete response': 'Delete response',
    'Email service is not configured. Contact your administrator to enable SMTP settings.':
        'Email service is not configured. Contact your administrator to enable SMTP settings.',
    'Daily Email Notifications': 'Daily Email Notifications',
    'Email Notifications': 'Email Notifications',
    'Receive a daily summary of new survey responses via email.':
        'Receive a daily summary of new survey responses via email.',
    'Send an email every time a new response is submitted.':
        'Send an email every time a new response is submitted.',
    'Recipient Email': 'Recipient Email',
    'Email is required': 'Email is required',
    'Enter a valid email address': 'Enter a valid email address',
    'Send Time (UTC)': 'Send Time (UTC)',
    'Create Settings': 'Create Settings',
    'Save Changes': 'Save Changes',
    'Enable Notifications': 'Enable Notifications',
    'Daily notifications are active': 'Daily notifications are active',
    'Daily notifications are paused': 'Daily notifications are paused',
    'Response notifications are active': 'Response notifications are active',
    'Response notifications are paused': 'Response notifications are paused',
    'Last Sent': 'Last Sent',
    'Send Test Notification': 'Send Test Notification',
    'Loading...': 'Loading...',
    'Survey Not Found': 'Survey Not Found',
    'Survey not found': 'Survey not found',
    'Back to Dashboard': 'Back to Dashboard',
    'This survey is archived. You cannot edit the questions.':
        'This survey is archived. You cannot edit the questions.',
    'Publish Survey': 'Publish Survey',
    'Publish survey confirmation':
        'Are you sure you want to publish this survey?\n\nOnce published, you will not be able to edit the questions.',
    'Title': 'Title',
    'Enter survey title': 'Enter survey title',
    'Title is required': 'Title is required',
    'Other languages': 'Other languages',
    'URL Slug': 'URL Slug',
    'Slug is required': 'Slug is required',
    'Only lowercase letters, numbers, and hyphens allowed':
        'Only lowercase letters, numbers, and hyphens allowed',
    'Custom domain (optional)': 'Custom domain (optional)',
    'Use a dedicated host to open this survey without a slug.':
        'Use a dedicated host to open this survey without a slug.',
    'Custom domain must be a hostname like forms.example.com':
        'Custom domain must be a hostname like forms.example.com',
    'Description (optional)': 'Description (optional)',
    'Brief description of the survey': 'Brief description of the survey',
    'Questions': 'Questions',
    'No questions yet': 'No questions yet',
    'Add questions to your survey': 'Add questions to your survey',
    'Add Question': 'Add Question',
    'Delete Question': 'Delete Question',
    'Delete question confirmation':
        'Are you sure you want to delete this question?\n\n"{question}"\n\nThis will also delete any responses to this question.',
    'Single Choice': 'Single Choice',
    'Multiple Choice': 'Multiple Choice',
    'Short Text': 'Short Text',
    'Long Text': 'Long Text',
    'Visible when {count} rule matches': 'Visible when {count} rule matches',
    'Visible when {count} rules match': 'Visible when {count} rules match',
    'Edit question': 'Edit question',
    'Delete question': 'Delete question',
    'Placeholder: {placeholder}': 'Placeholder: {placeholder}',
    'min {value}': 'min {value}',
    'max {value}': 'max {value}',
    'Length: {summary}': 'Length: {summary}',
    'Selections: {summary}': 'Selections: {summary}',
    'Edit Question': 'Edit Question',
    'Question text': 'Question text',
    'Enter your question': 'Enter your question',
    'Question text is required': 'Question text is required',
    'Question Type': 'Question Type',
    'Placeholder (optional)': 'Placeholder (optional)',
    'Placeholder text for the input': 'Placeholder text for the input',
    'Min length': 'Min length',
    'Max length': 'Max length',
    'Min selections': 'Min selections',
    'Max selections': 'Max selections',
    'Visibility rule match': 'Visibility rule match',
    'All rules': 'All rules',
    'Any rule': 'Any rule',
    'Required': 'Required',
    'Respondents must answer this question':
        'Respondents must answer this question',
    'Save': 'Save',
    'Add': 'Add',
    'Use 0 or more': 'Use 0 or more',
    'Add Choice': 'Add Choice',
    'Add at least one choice for choice questions':
        'Add at least one choice for choice questions',
    'Choice text': 'Choice text',
    'Choice text is required': 'Choice text is required',
    'Visibility rules': 'Visibility rules',
    'Always visible': 'Always visible',
    '{count} rule': '{count} rule',
    '{count} rules': '{count} rules',
    'Add an earlier question before creating rules.':
        'Add an earlier question before creating rules.',
    'All': 'All',
    'Any': 'Any',
    'Add rule': 'Add rule',
    'Save rules': 'Save rules',
    'Question': 'Question',
    'Condition': 'Condition',
    'Delete rule': 'Delete rule',
    'Value': 'Value',
    'equals': 'equals',
    'does not equal': 'does not equal',
    'contains': 'contains',
    'does not contain': 'does not contain',
    'is answered': 'is answered',
    'is not answered': 'is not answered',
    'Generate with AI': 'Generate with AI',
    'Describe your survey and AI will generate questions for you.':
        'Describe your survey and AI will generate questions for you.',
    'Example: Onboarding survey for a fitness app asking about exercise experience, target weight, and weekly workout frequency':
        'Example: Onboarding survey for a fitness app asking about exercise experience, target weight, and weekly workout frequency',
    'Generating...': 'Generating...',
    'Generate': 'Generate',
    'Add manually': 'Add manually',
    'Generated Questions': 'Generated Questions',
    '{count} questions generated. Review and apply to your survey.':
        '{count} questions generated. Review and apply to your survey.',
    'Apply': 'Apply',
    'Choices': 'Choices',
    'No choices yet. Add at least one choice.':
        'No choices yet. Add at least one choice.',
    'Choice 1': 'Choice 1',
    'Choice 2': 'Choice 2',
    'Add User': 'Add User',
    'Back': 'Back',
    'No users yet': 'No users yet',
    'Add your first user to get started': 'Add your first user to get started',
    'Delete Your Account': 'Delete Your Account',
    'Delete User': 'Delete User',
    'Delete your account confirmation':
        'You are about to delete your currently logged-in account. You will be logged out immediately after deletion.\n\nAre you sure you want to proceed?',
    'Delete user confirmation': 'Are you sure you want to delete {email}?',
    'Create User': 'Create User',
    'Please enter a valid email': 'Please enter a valid email',
    'Password is required': 'Password is required',
    'Role': 'Role',
    'Viewer': 'Viewer',
    'Editor': 'Editor',
    'Admin': 'Admin',
    'Create': 'Create',
    'Can manage users, surveys, responses, and settings.':
        'Can manage users, surveys, responses, and settings.',
    'Can create surveys and manage responses.':
        'Can create surveys and manage responses.',
    'Can view surveys and responses only.':
        'Can view surveys and responses only.',
    'No email': 'No email',
    'You': 'You',
    'Blocked': 'Blocked',
    'Make admin': 'Make admin',
    'Make editor': 'Make editor',
    'Make viewer': 'Make viewer',
    'Unblock': 'Unblock',
    'Block': 'Block',
    'Invalid email or password': 'Invalid email or password',
    'Too many login attempts. Please try again later.':
        'Too many login attempts. Please try again later.',
    'Login failed. Please try again.': 'Login failed. Please try again.',
    'Invalid state. Please start over.': 'Invalid state. Please start over.',
    'Password reset successful! You can now login.':
        'Password reset successful! You can now login.',
    'Password reset is not available. Please contact an administrator.':
        'Password reset is not available. Please contact an administrator.',
    'Invalid verification code. Please try again.':
        'Invalid verification code. Please try again.',
    'The verification code has expired. Please request a new one.':
        'The verification code has expired. Please request a new one.',
    'Too many attempts. Please try again later.':
        'Too many attempts. Please try again later.',
    'An error occurred. Please try again.':
        'An error occurred. Please try again.',
    'Settings saved successfully': 'Settings saved successfully',
    'Gemini': 'Gemini',
    'Gemini API Key': 'Gemini API Key',
    'Leave blank to keep the saved key': 'Leave blank to keep the saved key',
    'Clear saved Gemini API key': 'Clear saved Gemini API key',
    'SMTP Server': 'SMTP Server',
    'SMTP Host': 'SMTP Host',
    'SMTP Port': 'SMTP Port',
    'Username (optional)': 'Username (optional)',
    'SMTP Password': 'SMTP Password',
    'Leave blank to keep the saved password':
        'Leave blank to keep the saved password',
    'Clear saved SMTP password': 'Clear saved SMTP password',
    'From Email': 'From Email',
    'From Name (optional)': 'From Name (optional)',
    'Security': 'Security',
    'STARTTLS': 'STARTTLS',
    'TLS': 'TLS',
    'None': 'None',
    'Configured': 'Configured',
    'Not configured': 'Not configured',
    'Host is required when SMTP settings are present':
        'Host is required when SMTP settings are present',
    'Port is required when SMTP settings are present':
        'Port is required when SMTP settings are present',
    'Port must be between 1 and 65535': 'Port must be between 1 and 65535',
    'From email is required when SMTP settings are present':
        'From email is required when SMTP settings are present',
    'Insufficient permissions': 'Insufficient permissions',
    'Notifications enabled': 'Notifications enabled',
    'Notifications disabled': 'Notifications disabled',
    'Test notification sent': 'Test notification sent',
    'File downloads are only available on web.':
        'File downloads are only available on web.',
    'Registration failed: ': 'Registration failed: {error}',
    'Failed to load config: ': 'Failed to load config: {error}',
    'Failed to load surveys: ': 'Failed to load surveys: {error}',
    'Failed to delete survey: ': 'Failed to delete survey: {error}',
    'Failed to publish survey: ': 'Failed to publish survey: {error}',
    'Failed to close survey: ': 'Failed to close survey: {error}',
    'Failed to reopen survey: ': 'Failed to reopen survey: {error}',
    'Failed to update web publication: ':
        'Failed to update web publication: {error}',
    'Failed to load survey: ': 'Failed to load survey: {error}',
    'Failed to load questions: ': 'Failed to load questions: {error}',
    'Failed to create question: ': 'Failed to create question: {error}',
    'Failed to update question: ': 'Failed to update question: {error}',
    'Failed to delete question: ': 'Failed to delete question: {error}',
    'Failed to reorder questions: ': 'Failed to reorder questions: {error}',
    'Failed to create choice: ': 'Failed to create choice: {error}',
    'Failed to update choice: ': 'Failed to update choice: {error}',
    'Failed to delete choice: ': 'Failed to delete choice: {error}',
    'Failed to save visibility rules: ':
        'Failed to save visibility rules: {error}',
    'Failed to create survey: ': 'Failed to create survey: {error}',
    'Failed to update survey: ': 'Failed to update survey: {error}',
    'Failed to generate questions: ': 'Failed to generate questions: {error}',
    'Failed to load results: ': 'Failed to load results: {error}',
    'Failed to load responses: ': 'Failed to load responses: {error}',
    'Failed to export responses: ': 'Failed to export responses: {error}',
    'Failed to delete response: ': 'Failed to delete response: {error}',
    'Failed to send reply: ': 'Failed to send reply: {error}',
    'Failed to load notification settings: ':
        'Failed to load notification settings: {error}',
    'Failed to load settings: ': 'Failed to load settings: {error}',
    'Failed to save settings: ': 'Failed to save settings: {error}',
    'Failed to toggle notifications: ':
        'Failed to toggle notifications: {error}',
    'Failed to send test notification: ':
        'Failed to send test notification: {error}',
    'Failed to load users: ': 'Failed to load users: {error}',
    'Failed to create user: ': 'Failed to create user: {error}',
    'Failed to update role: ': 'Failed to update role: {error}',
    'Failed to delete user: ': 'Failed to delete user: {error}',
    'Failed to update user: ': 'Failed to update user: {error}',
  },
  'ja': {
    'Form Concierge Admin': 'Form Concierge Admin',
    'Form Concierge': 'Form Concierge',
    'Admin Dashboard': '管理ダッシュボード',
    'Welcome! Create your admin account to get started.':
        'ようこそ。開始するには管理者アカウントを作成してください。',
    'Email': 'メールアドレス',
    'Password': 'パスワード',
    'Forgot Password?': 'パスワードをお忘れですか？',
    'Create Account': 'アカウントを作成',
    'Login': 'ログイン',
    'Forgot Password': 'パスワードを忘れた場合',
    'Reset Your Password': 'パスワードをリセット',
    "Enter your email address and we'll send you a verification code.":
        'メールアドレスを入力すると確認コードを送信します。',
    'Send Code': 'コードを送信',
    'Back to Login': 'ログインに戻る',
    'Verify Code': 'コードを確認',
    'Check Your Email': 'メールを確認してください',
    'We sent a verification code to:': '確認コードの送信先:',
    'Verification Code': '確認コード',
    'Enter 6-digit code': '6桁のコードを入力',
    'Verify': '確認',
    'Cancel': 'キャンセル',
    'Password Reset Complete': 'パスワードのリセット完了',
    'Your password has been successfully reset. You can now login with your new password.':
        'パスワードをリセットしました。新しいパスワードでログインできます。',
    'Go to Login': 'ログインへ',
    'New Password': '新しいパスワード',
    'Create New Password': '新しいパスワードを作成',
    'Enter a new password for your account.': 'アカウントの新しいパスワードを入力してください。',
    'Confirm Password': 'パスワードを確認',
    'Reset Password': 'パスワードをリセット',
    'Please enter a password': 'パスワードを入力してください',
    'Password must be at least 8 characters': 'パスワードは8文字以上にしてください',
    'Passwords do not match': 'パスワードが一致しません',
    'Surveys': 'アンケート',
    'Refresh': '再読み込み',
    'User Management': 'ユーザー管理',
    'Settings': '設定',
    'Logout': 'ログアウト',
    'New Survey': '新しいアンケート',
    'Retry': '再試行',
    'No surveys yet': 'アンケートはまだありません',
    'Create your first survey to get started': '最初のアンケートを作成して開始します',
    'Create Survey': 'アンケートを作成',
    'Web public': 'Web公開',
    'New Project': '新しいプロジェクト',
    'Project Settings': 'プロジェクト設定',
    'Project not found': 'プロジェクトが見つかりません',
    'Create Project': 'プロジェクトを作成',
    'Project URL Slug': 'プロジェクトURLスラッグ',
    'Use a dedicated host to open this project without a slug.':
        '専用ホストでスラッグなしにこのプロジェクトを開けます。',
    'Localized project names': 'プロジェクト名の多言語入力',
    'Project name': 'プロジェクト名',
    'Enter project name': 'プロジェクト名を入力',
    'Project name is required': 'プロジェクト名は必須です',
    'Brief description of the project': 'プロジェクトの簡単な説明',
    'Delete Survey': 'アンケートを削除',
    'Delete survey confirmation':
        '「{title}」を削除してもよろしいですか？\n\n関連する質問と回答もすべて削除されます。この操作は元に戻せません。',
    'Publish': '公開',
    'Close': '終了',
    'Reopen': '再開',
    'View Responses': '回答を見る',
    'Delete': '削除',
    'Draft': '下書き',
    'Published': '公開中',
    'Closed': '終了',
    'Archived': 'アーカイブ済み',
    'Responses': '回答',
    'Export responses': '回答をエクスポート',
    'Export CSV': 'CSVをエクスポート',
    'Export JSON': 'JSONをエクスポート',
    'Results': '集計',
    'Individual': '個別',
    'Notifications': '通知',
    'Delete Response': '回答を削除',
    'Delete response confirmation': 'この回答を削除してもよろしいですか？\n\nこの操作は元に戻せません。',
    'Reply to respondent': '回答者に返信',
    'Message': 'メッセージ',
    'Send': '送信',
    'Reply sent': '返信を送信しました',
    'Exported {filename}': '{filename} をエクスポートしました',
    'No responses yet': '回答はまだありません',
    'Share your survey to start collecting responses': '回答を集めるにはアンケートを共有してください',
    'Total Responses': '総回答数',
    'Results by Question': '質問ごとの結果',
    'Choice': '選択肢',
    'Count': '件数',
    'No text responses': 'テキスト回答はありません',
    '{count} response': '{count}件の回答',
    '{count} responses': '{count}件の回答',
    '... and {count} more responses': '... 他 {count} 件の回答',
    'Previous page': '前のページ',
    'Next page': '次のページ',
    'Page {currentPage} of {totalPages}': '{currentPage} / {totalPages} ページ',
    'User #{id}': 'ユーザー #{id}',
    'Anonymous': '匿名',
    'Reply': '返信',
    'Delete response': '回答を削除',
    'Email service is not configured. Contact your administrator to enable SMTP settings.':
        'メールサービスが設定されていません。SMTP設定を有効にするには管理者に連絡してください。',
    'Daily Email Notifications': '毎日のメール通知',
    'Email Notifications': 'メール通知',
    'Receive a daily summary of new survey responses via email.':
        '新しいアンケート回答のサマリーを毎日メールで受け取ります。',
    'Send an email every time a new response is submitted.':
        '新しい回答が送信されるたびにメールを送信します。',
    'Recipient Email': '宛先メールアドレス',
    'Email is required': 'メールアドレスは必須です',
    'Enter a valid email address': '有効なメールアドレスを入力してください',
    'Send Time (UTC)': '送信時刻 (UTC)',
    'Create Settings': '設定を作成',
    'Save Changes': '変更を保存',
    'Enable Notifications': '通知を有効化',
    'Daily notifications are active': '毎日の通知は有効です',
    'Daily notifications are paused': '毎日の通知は停止中です',
    'Response notifications are active': '回答通知は有効です',
    'Response notifications are paused': '回答通知は停止中です',
    'Last Sent': '最終送信',
    'Send Test Notification': 'テスト通知を送信',
    'Loading...': '読み込み中...',
    'Survey Not Found': 'アンケートが見つかりません',
    'Survey not found': 'アンケートが見つかりません',
    'Back to Dashboard': 'ダッシュボードに戻る',
    'This survey is archived. You cannot edit the questions.':
        'このアンケートはアーカイブ済みです。質問は編集できません。',
    'Publish Survey': 'アンケートを公開',
    'Publish survey confirmation':
        'このアンケートを公開してもよろしいですか？\n\n公開後は質問を編集できなくなります。',
    'Title': 'タイトル',
    'Enter survey title': 'アンケートのタイトルを入力',
    'Title is required': 'タイトルは必須です',
    'Other languages': '他の言語',
    'URL Slug': 'URLスラッグ',
    'Slug is required': 'スラッグは必須です',
    'Only lowercase letters, numbers, and hyphens allowed':
        '小文字、数字、ハイフンのみ使用できます',
    'Custom domain (optional)': 'カスタムドメイン (任意)',
    'Use a dedicated host to open this survey without a slug.':
        '専用ホストでスラッグなしにこのアンケートを開けます。',
    'Custom domain must be a hostname like forms.example.com':
        'カスタムドメインは forms.example.com のようなホスト名にしてください',
    'Description (optional)': '説明 (任意)',
    'Brief description of the survey': 'アンケートの簡単な説明',
    'Questions': '質問',
    'No questions yet': '質問はまだありません',
    'Add questions to your survey': 'アンケートに質問を追加してください',
    'Add Question': '質問を追加',
    'Delete Question': '質問を削除',
    'Delete question confirmation':
        'この質問を削除してもよろしいですか？\n\n「{question}」\n\nこの質問への回答も削除されます。',
    'Single Choice': '単一選択',
    'Multiple Choice': '複数選択',
    'Short Text': '短文',
    'Long Text': '長文',
    'Visible when {count} rule matches': '{count}件のルールに一致したとき表示',
    'Visible when {count} rules match': '{count}件のルールに一致したとき表示',
    'Edit question': '質問を編集',
    'Delete question': '質問を削除',
    'Placeholder: {placeholder}': 'プレースホルダー: {placeholder}',
    'min {value}': '最小 {value}',
    'max {value}': '最大 {value}',
    'Length: {summary}': '文字数: {summary}',
    'Selections: {summary}': '選択数: {summary}',
    'Edit Question': '質問を編集',
    'Question text': '質問文',
    'Enter your question': '質問を入力',
    'Question text is required': '質問文は必須です',
    'Question Type': '質問タイプ',
    'Placeholder (optional)': 'プレースホルダー (任意)',
    'Placeholder text for the input': '入力欄のプレースホルダーテキスト',
    'Min length': '最小文字数',
    'Max length': '最大文字数',
    'Min selections': '最小選択数',
    'Max selections': '最大選択数',
    'Visibility rule match': '表示ルールの一致条件',
    'All rules': 'すべてのルール',
    'Any rule': 'いずれかのルール',
    'Required': '必須',
    'Respondents must answer this question': '回答者はこの質問に回答する必要があります',
    'Save': '保存',
    'Add': '追加',
    'Use 0 or more': '0以上を入力してください',
    'Add Choice': '選択肢を追加',
    'Add at least one choice for choice questions':
        '選択式の質問には少なくとも1つの選択肢を追加してください',
    'Choice text': '選択肢のテキスト',
    'Choice text is required': '選択肢のテキストは必須です',
    'Visibility rules': '表示ルール',
    'Always visible': '常に表示',
    '{count} rule': '{count}件のルール',
    '{count} rules': '{count}件のルール',
    'Add an earlier question before creating rules.':
        'ルールを作成する前に前の質問を追加してください。',
    'All': 'すべて',
    'Any': 'いずれか',
    'Add rule': 'ルールを追加',
    'Save rules': 'ルールを保存',
    'Question': '質問',
    'Condition': '条件',
    'Delete rule': 'ルールを削除',
    'Value': '値',
    'equals': '等しい',
    'does not equal': '等しくない',
    'contains': '含む',
    'does not contain': '含まない',
    'is answered': '回答済み',
    'is not answered': '未回答',
    'Generate with AI': 'AIで生成',
    'Describe your survey and AI will generate questions for you.':
        'アンケートの内容を説明すると、AIが質問を生成します。',
    'Example: Onboarding survey for a fitness app asking about exercise experience, target weight, and weekly workout frequency':
        '例: 運動経験、目標体重、週の運動頻度を尋ねるフィットネスアプリのオンボーディングアンケート',
    'Generating...': '生成中...',
    'Generate': '生成',
    'Add manually': '手動で追加',
    'Generated Questions': '生成された質問',
    '{count} questions generated. Review and apply to your survey.':
        '{count}件の質問が生成されました。確認してアンケートに適用してください。',
    'Apply': '適用',
    'Choices': '選択肢',
    'No choices yet. Add at least one choice.': '選択肢はまだありません。少なくとも1つ追加してください。',
    'Choice 1': '選択肢 1',
    'Choice 2': '選択肢 2',
    'Add User': 'ユーザーを追加',
    'Back': '戻る',
    'No users yet': 'ユーザーはまだいません',
    'Add your first user to get started': '最初のユーザーを追加して開始します',
    'Delete Your Account': '自分のアカウントを削除',
    'Delete User': 'ユーザーを削除',
    'Delete your account confirmation':
        '現在ログイン中のアカウントを削除しようとしています。削除後すぐにログアウトされます。\n\n続行してもよろしいですか？',
    'Delete user confirmation': '{email} を削除してもよろしいですか？',
    'Create User': 'ユーザーを作成',
    'Please enter a valid email': '有効なメールアドレスを入力してください',
    'Password is required': 'パスワードは必須です',
    'Role': 'ロール',
    'Viewer': '閲覧者',
    'Editor': '編集者',
    'Admin': '管理者',
    'Create': '作成',
    'Can manage users, surveys, responses, and settings.':
        'ユーザー、アンケート、回答、設定を管理できます。',
    'Can create surveys and manage responses.': 'アンケートを作成し、回答を管理できます。',
    'Can view surveys and responses only.': 'アンケートと回答の閲覧のみ可能です。',
    'No email': 'メールアドレスなし',
    'You': '自分',
    'Blocked': 'ブロック中',
    'Make admin': '管理者にする',
    'Make editor': '編集者にする',
    'Make viewer': '閲覧者にする',
    'Unblock': 'ブロック解除',
    'Block': 'ブロック',
    'Invalid email or password': 'メールアドレスまたはパスワードが無効です',
    'Too many login attempts. Please try again later.':
        'ログイン試行回数が多すぎます。後でもう一度お試しください。',
    'Login failed. Please try again.': 'ログインに失敗しました。もう一度お試しください。',
    'Invalid state. Please start over.': '状態が無効です。最初からやり直してください。',
    'Password reset successful! You can now login.': 'パスワードをリセットしました。ログインできます。',
    'Password reset is not available. Please contact an administrator.':
        'パスワードリセットは利用できません。管理者に連絡してください。',
    'Invalid verification code. Please try again.': '確認コードが無効です。もう一度お試しください。',
    'The verification code has expired. Please request a new one.':
        '確認コードの有効期限が切れています。新しいコードをリクエストしてください。',
    'Too many attempts. Please try again later.': '試行回数が多すぎます。後でもう一度お試しください。',
    'An error occurred. Please try again.': 'エラーが発生しました。もう一度お試しください。',
    'Settings saved successfully': '設定を保存しました',
    'Gemini': 'Gemini',
    'Gemini API Key': 'Gemini APIキー',
    'Leave blank to keep the saved key': '空欄のままなら保存済みのキーを維持します',
    'Clear saved Gemini API key': '保存済みのGemini APIキーを削除',
    'SMTP Server': 'SMTPサーバー',
    'SMTP Host': 'SMTPホスト',
    'SMTP Port': 'SMTPポート',
    'Username (optional)': 'ユーザー名 (任意)',
    'SMTP Password': 'SMTPパスワード',
    'Leave blank to keep the saved password': '空欄のままなら保存済みのパスワードを維持します',
    'Clear saved SMTP password': '保存済みのSMTPパスワードを削除',
    'From Email': '送信元メールアドレス',
    'From Name (optional)': '送信者名 (任意)',
    'Security': 'セキュリティ',
    'STARTTLS': 'STARTTLS',
    'TLS': 'TLS',
    'None': 'なし',
    'Configured': '設定済み',
    'Not configured': '未設定',
    'Host is required when SMTP settings are present': 'SMTP設定を入力する場合はホストが必須です',
    'Port is required when SMTP settings are present': 'SMTP設定を入力する場合はポートが必須です',
    'Port must be between 1 and 65535': 'ポートは1から65535の範囲で入力してください',
    'From email is required when SMTP settings are present':
        'SMTP設定を入力する場合は送信元メールアドレスが必須です',
    'Insufficient permissions': '権限がありません',
    'Notifications enabled': '通知を有効にしました',
    'Notifications disabled': '通知を無効にしました',
    'Test notification sent': 'テスト通知を送信しました',
    'File downloads are only available on web.': 'ファイルのダウンロードはWebでのみ利用できます。',
    'Registration failed: ': '登録に失敗しました: {error}',
    'Failed to load config: ': '設定の読み込みに失敗しました: {error}',
    'Failed to load surveys: ': 'アンケートの読み込みに失敗しました: {error}',
    'Failed to delete survey: ': 'アンケートの削除に失敗しました: {error}',
    'Failed to publish survey: ': 'アンケートの公開に失敗しました: {error}',
    'Failed to close survey: ': 'アンケートの終了に失敗しました: {error}',
    'Failed to reopen survey: ': 'アンケートの再開に失敗しました: {error}',
    'Failed to update web publication: ': 'Web公開設定の更新に失敗しました: {error}',
    'Failed to load survey: ': 'アンケートの読み込みに失敗しました: {error}',
    'Failed to load questions: ': '質問の読み込みに失敗しました: {error}',
    'Failed to create question: ': '質問の作成に失敗しました: {error}',
    'Failed to update question: ': '質問の更新に失敗しました: {error}',
    'Failed to delete question: ': '質問の削除に失敗しました: {error}',
    'Failed to reorder questions: ': '質問の並べ替えに失敗しました: {error}',
    'Failed to create choice: ': '選択肢の作成に失敗しました: {error}',
    'Failed to update choice: ': '選択肢の更新に失敗しました: {error}',
    'Failed to delete choice: ': '選択肢の削除に失敗しました: {error}',
    'Failed to save visibility rules: ': '表示ルールの保存に失敗しました: {error}',
    'Failed to create survey: ': 'アンケートの作成に失敗しました: {error}',
    'Failed to update survey: ': 'アンケートの更新に失敗しました: {error}',
    'Failed to generate questions: ': '質問の生成に失敗しました: {error}',
    'Failed to load results: ': '結果の読み込みに失敗しました: {error}',
    'Failed to load responses: ': '回答の読み込みに失敗しました: {error}',
    'Failed to export responses: ': '回答のエクスポートに失敗しました: {error}',
    'Failed to delete response: ': '回答の削除に失敗しました: {error}',
    'Failed to send reply: ': '返信の送信に失敗しました: {error}',
    'Failed to load notification settings: ': '通知設定の読み込みに失敗しました: {error}',
    'Failed to load settings: ': '設定の読み込みに失敗しました: {error}',
    'Failed to save settings: ': '設定の保存に失敗しました: {error}',
    'Failed to toggle notifications: ': '通知の切り替えに失敗しました: {error}',
    'Failed to send test notification: ': 'テスト通知の送信に失敗しました: {error}',
    'Failed to load users: ': 'ユーザーの読み込みに失敗しました: {error}',
    'Failed to create user: ': 'ユーザーの作成に失敗しました: {error}',
    'Failed to update role: ': 'ロールの更新に失敗しました: {error}',
    'Failed to delete user: ': 'ユーザーの削除に失敗しました: {error}',
    'Failed to update user: ': 'ユーザーの更新に失敗しました: {error}',
  },
  'zh_Hans': {
    'Form Concierge Admin': 'Form Concierge Admin',
    'Form Concierge': 'Form Concierge',
    'Admin Dashboard': '管理仪表板',
    'Welcome! Create your admin account to get started.': '欢迎！创建管理员账户即可开始。',
    'Email': '电子邮件',
    'Password': '密码',
    'Forgot Password?': '忘记密码？',
    'Create Account': '创建账户',
    'Login': '登录',
    'Forgot Password': '忘记密码',
    'Reset Your Password': '重置密码',
    "Enter your email address and we'll send you a verification code.":
        '输入电子邮件地址，我们会发送验证码。',
    'Send Code': '发送验证码',
    'Back to Login': '返回登录',
    'Verify Code': '验证码',
    'Check Your Email': '检查电子邮件',
    'We sent a verification code to:': '验证码已发送至：',
    'Verification Code': '验证码',
    'Enter 6-digit code': '输入6位验证码',
    'Verify': '验证',
    'Cancel': '取消',
    'Password Reset Complete': '密码重置完成',
    'Your password has been successfully reset. You can now login with your new password.':
        '密码已成功重置。现在可以使用新密码登录。',
    'Go to Login': '前往登录',
    'New Password': '新密码',
    'Create New Password': '创建新密码',
    'Enter a new password for your account.': '输入账户的新密码。',
    'Confirm Password': '确认密码',
    'Reset Password': '重置密码',
    'Please enter a password': '请输入密码',
    'Password must be at least 8 characters': '密码至少需要8个字符',
    'Passwords do not match': '两次密码不一致',
    'Surveys': '问卷',
    'Refresh': '刷新',
    'User Management': '用户管理',
    'Logout': '退出登录',
    'New Survey': '新建问卷',
    'Retry': '重试',
    'No surveys yet': '还没有问卷',
    'Create your first survey to get started': '创建第一个问卷即可开始',
    'Create Survey': '创建问卷',
    'Delete Survey': '删除问卷',
    'Delete survey confirmation': '确定要删除“{title}”吗？\n\n这也会删除所有问题和回答。此操作无法撤销。',
    'Publish': '发布',
    'Close': '关闭',
    'Reopen': '重新开启',
    'View Responses': '查看回答',
    'Delete': '删除',
    'Draft': '草稿',
    'Published': '已发布',
    'Closed': '已关闭',
    'Archived': '已归档',
    'Responses': '回答',
    'Export responses': '导出回答',
    'Export CSV': '导出 CSV',
    'Export JSON': '导出 JSON',
    'Results': '结果',
    'Individual': '单条',
    'Notifications': '通知',
    'Delete Response': '删除回答',
    'Delete response confirmation': '确定要删除此回答吗？\n\n此操作无法撤销。',
    'Reply to respondent': '回复回答者',
    'Message': '消息',
    'Send': '发送',
    'Reply sent': '回复已发送',
    'Exported {filename}': '已导出 {filename}',
    'No responses yet': '还没有回答',
    'Share your survey to start collecting responses': '分享问卷即可开始收集回答',
    'Total Responses': '总回答数',
    'Results by Question': '按问题查看结果',
    'Choice': '选项',
    'Count': '数量',
    'No text responses': '没有文本回答',
    '{count} response': '{count} 条回答',
    '{count} responses': '{count} 条回答',
    '... and {count} more responses': '... 还有 {count} 条回答',
    'Previous page': '上一页',
    'Next page': '下一页',
    'Page {currentPage} of {totalPages}': '第 {currentPage} 页，共 {totalPages} 页',
    'User #{id}': '用户 #{id}',
    'Anonymous': '匿名',
    'Reply': '回复',
    'Delete response': '删除回答',
    'Email service is not configured. Contact your administrator to enable SMTP settings.':
        '尚未配置邮件服务。请联系管理员启用 SMTP 设置。',
    'Daily Email Notifications': '每日邮件通知',
    'Receive a daily summary of new survey responses via email.':
        '通过电子邮件接收新问卷回答的每日摘要。',
    'Recipient Email': '收件人电子邮件',
    'Email is required': '电子邮件为必填项',
    'Enter a valid email address': '请输入有效的电子邮件地址',
    'Send Time (UTC)': '发送时间 (UTC)',
    'Create Settings': '创建设置',
    'Save Changes': '保存更改',
    'Enable Notifications': '启用通知',
    'Daily notifications are active': '每日通知已启用',
    'Daily notifications are paused': '每日通知已暂停',
    'Last Sent': '上次发送',
    'Send Test Notification': '发送测试通知',
    'Loading...': '正在加载...',
    'Survey Not Found': '未找到问卷',
    'Survey not found': '未找到问卷',
    'Back to Dashboard': '返回仪表板',
    'This survey is archived. You cannot edit the questions.':
        '此问卷已归档。你无法编辑问题。',
    'Publish Survey': '发布问卷',
    'Publish survey confirmation': '确定要发布此问卷吗？\n\n发布后将无法编辑问题。',
    'Title': '标题',
    'Enter survey title': '输入问卷标题',
    'Title is required': '标题为必填项',
    'Other languages': '其他语言',
    'URL Slug': 'URL 标识',
    'Slug is required': 'URL 标识为必填项',
    'Only lowercase letters, numbers, and hyphens allowed': '只能使用小写字母、数字和连字符',
    'Description (optional)': '描述（可选）',
    'Brief description of the survey': '问卷的简短描述',
    'Questions': '问题',
    'No questions yet': '还没有问题',
    'Add questions to your survey': '向问卷添加问题',
    'Add Question': '添加问题',
    'Delete Question': '删除问题',
    'Delete question confirmation':
        '确定要删除此问题吗？\n\n“{question}”\n\n此问题的所有回答也会被删除。',
    'Single Choice': '单选',
    'Multiple Choice': '多选',
    'Short Text': '短文本',
    'Long Text': '长文本',
    'Visible when {count} rule matches': '当 {count} 条规则匹配时显示',
    'Visible when {count} rules match': '当 {count} 条规则匹配时显示',
    'Edit question': '编辑问题',
    'Delete question': '删除问题',
    'Placeholder: {placeholder}': '占位符：{placeholder}',
    'min {value}': '最小 {value}',
    'max {value}': '最大 {value}',
    'Length: {summary}': '长度：{summary}',
    'Selections: {summary}': '选择数：{summary}',
    'Edit Question': '编辑问题',
    'Question text': '问题文本',
    'Enter your question': '输入你的问题',
    'Question text is required': '问题文本为必填项',
    'Question Type': '问题类型',
    'Placeholder (optional)': '占位符（可选）',
    'Placeholder text for the input': '输入框的占位符文本',
    'Min length': '最小长度',
    'Max length': '最大长度',
    'Min selections': '最少选择数',
    'Max selections': '最多选择数',
    'Visibility rule match': '可见性规则匹配',
    'All rules': '所有规则',
    'Any rule': '任一规则',
    'Required': '必填',
    'Respondents must answer this question': '回答者必须回答此问题',
    'Save': '保存',
    'Add': '添加',
    'Use 0 or more': '请输入0或更大的数',
    'Add Choice': '添加选项',
    'Add at least one choice for choice questions': '选择题至少需要添加一个选项',
    'Choice text': '选项文本',
    'Choice text is required': '选项文本为必填项',
    'Visibility rules': '可见性规则',
    'Always visible': '始终显示',
    '{count} rule': '{count} 条规则',
    '{count} rules': '{count} 条规则',
    'Add an earlier question before creating rules.': '请先添加前置问题，然后再创建规则。',
    'All': '全部',
    'Any': '任一',
    'Add rule': '添加规则',
    'Save rules': '保存规则',
    'Question': '问题',
    'Condition': '条件',
    'Delete rule': '删除规则',
    'Value': '值',
    'equals': '等于',
    'does not equal': '不等于',
    'contains': '包含',
    'does not contain': '不包含',
    'is answered': '已回答',
    'is not answered': '未回答',
    'Generate with AI': '用 AI 生成',
    'Describe your survey and AI will generate questions for you.':
        '描述你的问卷，AI 会为你生成问题。',
    'Example: Onboarding survey for a fitness app asking about exercise experience, target weight, and weekly workout frequency':
        '示例：健身应用的新用户问卷，询问运动经验、目标体重和每周锻炼频率',
    'Generating...': '正在生成...',
    'Generate': '生成',
    'Add manually': '手动添加',
    'Generated Questions': '生成的问题',
    '{count} questions generated. Review and apply to your survey.':
        '已生成 {count} 个问题。请检查并应用到问卷。',
    'Apply': '应用',
    'Choices': '选项',
    'No choices yet. Add at least one choice.': '还没有选项。请至少添加一个选项。',
    'Choice 1': '选项 1',
    'Choice 2': '选项 2',
    'Add User': '添加用户',
    'Back': '返回',
    'No users yet': '还没有用户',
    'Add your first user to get started': '添加第一个用户即可开始',
    'Delete Your Account': '删除你的账户',
    'Delete User': '删除用户',
    'Delete your account confirmation': '你即将删除当前登录的账户。删除后你会立即退出登录。\n\n确定要继续吗？',
    'Delete user confirmation': '确定要删除 {email} 吗？',
    'Create User': '创建用户',
    'Please enter a valid email': '请输入有效的电子邮件',
    'Password is required': '密码为必填项',
    'Role': '角色',
    'Viewer': '查看者',
    'Editor': '编辑者',
    'Admin': '管理员',
    'Create': '创建',
    'Can manage users, surveys, responses, and settings.': '可以管理用户、问卷、回答和设置。',
    'Can create surveys and manage responses.': '可以创建问卷并管理回答。',
    'Can view surveys and responses only.': '只能查看问卷和回答。',
    'No email': '没有电子邮件',
    'You': '你',
    'Blocked': '已封禁',
    'Make admin': '设为管理员',
    'Make editor': '设为编辑者',
    'Make viewer': '设为查看者',
    'Unblock': '解除封禁',
    'Block': '封禁',
    'Invalid email or password': '电子邮件或密码无效',
    'Too many login attempts. Please try again later.': '登录尝试次数过多。请稍后再试。',
    'Login failed. Please try again.': '登录失败。请重试。',
    'Invalid state. Please start over.': '状态无效。请重新开始。',
    'Password reset successful! You can now login.': '密码重置成功！现在可以登录。',
    'Password reset is not available. Please contact an administrator.':
        '密码重置不可用。请联系管理员。',
    'Invalid verification code. Please try again.': '验证码无效。请重试。',
    'The verification code has expired. Please request a new one.':
        '验证码已过期。请请求新的验证码。',
    'Too many attempts. Please try again later.': '尝试次数过多。请稍后再试。',
    'An error occurred. Please try again.': '发生错误。请重试。',
    'Settings saved successfully': '设置已保存',
    'Notifications enabled': '通知已启用',
    'Notifications disabled': '通知已禁用',
    'Test notification sent': '测试通知已发送',
    'File downloads are only available on web.': '文件下载仅在 Web 上可用。',
    'Registration failed: ': '注册失败：{error}',
    'Failed to load config: ': '加载配置失败：{error}',
    'Failed to load surveys: ': '加载问卷失败：{error}',
    'Failed to delete survey: ': '删除问卷失败：{error}',
    'Failed to publish survey: ': '发布问卷失败：{error}',
    'Failed to close survey: ': '关闭问卷失败：{error}',
    'Failed to reopen survey: ': '重新开启问卷失败：{error}',
    'Failed to load survey: ': '加载问卷失败：{error}',
    'Failed to load questions: ': '加载问题失败：{error}',
    'Failed to create question: ': '创建问题失败：{error}',
    'Failed to update question: ': '更新问题失败：{error}',
    'Failed to delete question: ': '删除问题失败：{error}',
    'Failed to reorder questions: ': '重新排序问题失败：{error}',
    'Failed to create choice: ': '创建选项失败：{error}',
    'Failed to update choice: ': '更新选项失败：{error}',
    'Failed to delete choice: ': '删除选项失败：{error}',
    'Failed to save visibility rules: ': '保存可见性规则失败：{error}',
    'Failed to create survey: ': '创建问卷失败：{error}',
    'Failed to update survey: ': '更新问卷失败：{error}',
    'Failed to generate questions: ': '生成问题失败：{error}',
    'Failed to load results: ': '加载结果失败：{error}',
    'Failed to load responses: ': '加载回答失败：{error}',
    'Failed to export responses: ': '导出回答失败：{error}',
    'Failed to delete response: ': '删除回答失败：{error}',
    'Failed to send reply: ': '发送回复失败：{error}',
    'Failed to load notification settings: ': '加载通知设置失败：{error}',
    'Failed to save settings: ': '保存设置失败：{error}',
    'Failed to toggle notifications: ': '切换通知失败：{error}',
    'Failed to send test notification: ': '发送测试通知失败：{error}',
    'Failed to load users: ': '加载用户失败：{error}',
    'Failed to create user: ': '创建用户失败：{error}',
    'Failed to update role: ': '更新角色失败：{error}',
    'Failed to delete user: ': '删除用户失败：{error}',
    'Failed to update user: ': '更新用户失败：{error}',
  },
  'zh_Hant': {
    'Form Concierge Admin': 'Form Concierge Admin',
    'Form Concierge': 'Form Concierge',
    'Admin Dashboard': '管理儀表板',
    'Welcome! Create your admin account to get started.': '歡迎！建立管理員帳戶即可開始。',
    'Email': '電子郵件',
    'Password': '密碼',
    'Forgot Password?': '忘記密碼？',
    'Create Account': '建立帳戶',
    'Login': '登入',
    'Forgot Password': '忘記密碼',
    'Reset Your Password': '重設密碼',
    "Enter your email address and we'll send you a verification code.":
        '輸入電子郵件地址，我們會傳送驗證碼。',
    'Send Code': '傳送驗證碼',
    'Back to Login': '返回登入',
    'Verify Code': '驗證碼',
    'Check Your Email': '檢查電子郵件',
    'We sent a verification code to:': '驗證碼已傳送至：',
    'Verification Code': '驗證碼',
    'Enter 6-digit code': '輸入6位驗證碼',
    'Verify': '驗證',
    'Cancel': '取消',
    'Password Reset Complete': '密碼重設完成',
    'Your password has been successfully reset. You can now login with your new password.':
        '密碼已成功重設。現在可以使用新密碼登入。',
    'Go to Login': '前往登入',
    'New Password': '新密碼',
    'Create New Password': '建立新密碼',
    'Enter a new password for your account.': '輸入帳戶的新密碼。',
    'Confirm Password': '確認密碼',
    'Reset Password': '重設密碼',
    'Please enter a password': '請輸入密碼',
    'Password must be at least 8 characters': '密碼至少需要8個字元',
    'Passwords do not match': '密碼不相符',
    'Surveys': '問卷',
    'Refresh': '重新整理',
    'User Management': '使用者管理',
    'Logout': '登出',
    'New Survey': '新增問卷',
    'Retry': '重試',
    'No surveys yet': '尚無問卷',
    'Create your first survey to get started': '建立第一份問卷即可開始',
    'Create Survey': '建立問卷',
    'Delete Survey': '刪除問卷',
    'Delete survey confirmation': '確定要刪除「{title}」嗎？\n\n這也會刪除所有問題和回答。此操作無法復原。',
    'Publish': '發布',
    'Close': '關閉',
    'Reopen': '重新開啟',
    'View Responses': '查看回答',
    'Delete': '刪除',
    'Draft': '草稿',
    'Published': '已發布',
    'Closed': '已關閉',
    'Archived': '已封存',
    'Responses': '回答',
    'Export responses': '匯出回答',
    'Export CSV': '匯出 CSV',
    'Export JSON': '匯出 JSON',
    'Results': '結果',
    'Individual': '個別',
    'Notifications': '通知',
    'Delete Response': '刪除回答',
    'Delete response confirmation': '確定要刪除此回答嗎？\n\n此操作無法復原。',
    'Reply to respondent': '回覆回答者',
    'Message': '訊息',
    'Send': '傳送',
    'Reply sent': '回覆已傳送',
    'Exported {filename}': '已匯出 {filename}',
    'No responses yet': '尚無回答',
    'Share your survey to start collecting responses': '分享問卷即可開始收集回答',
    'Total Responses': '總回答數',
    'Results by Question': '依問題查看結果',
    'Choice': '選項',
    'Count': '數量',
    'No text responses': '沒有文字回答',
    '{count} response': '{count} 則回答',
    '{count} responses': '{count} 則回答',
    '... and {count} more responses': '... 還有 {count} 則回答',
    'Previous page': '上一頁',
    'Next page': '下一頁',
    'Page {currentPage} of {totalPages}': '第 {currentPage} 頁，共 {totalPages} 頁',
    'User #{id}': '使用者 #{id}',
    'Anonymous': '匿名',
    'Reply': '回覆',
    'Delete response': '刪除回答',
    'Email service is not configured. Contact your administrator to enable SMTP settings.':
        '尚未設定郵件服務。請聯絡管理員啟用 SMTP 設定。',
    'Daily Email Notifications': '每日電子郵件通知',
    'Receive a daily summary of new survey responses via email.':
        '透過電子郵件接收新問卷回答的每日摘要。',
    'Recipient Email': '收件人電子郵件',
    'Email is required': '電子郵件為必填',
    'Enter a valid email address': '請輸入有效的電子郵件地址',
    'Send Time (UTC)': '傳送時間 (UTC)',
    'Create Settings': '建立設定',
    'Save Changes': '儲存變更',
    'Enable Notifications': '啟用通知',
    'Daily notifications are active': '每日通知已啟用',
    'Daily notifications are paused': '每日通知已暫停',
    'Last Sent': '上次傳送',
    'Send Test Notification': '傳送測試通知',
    'Loading...': '載入中...',
    'Survey Not Found': '找不到問卷',
    'Survey not found': '找不到問卷',
    'Back to Dashboard': '返回儀表板',
    'This survey is archived. You cannot edit the questions.':
        '此問卷已封存。你無法編輯問題。',
    'Publish Survey': '發布問卷',
    'Publish survey confirmation': '確定要發布此問卷嗎？\n\n發布後將無法編輯問題。',
    'Title': '標題',
    'Enter survey title': '輸入問卷標題',
    'Title is required': '標題為必填',
    'Other languages': '其他語言',
    'URL Slug': 'URL 識別碼',
    'Slug is required': 'URL 識別碼為必填',
    'Only lowercase letters, numbers, and hyphens allowed': '只能使用小寫字母、數字和連字號',
    'Description (optional)': '描述（選填）',
    'Brief description of the survey': '問卷的簡短描述',
    'Questions': '問題',
    'No questions yet': '尚無問題',
    'Add questions to your survey': '向問卷新增問題',
    'Add Question': '新增問題',
    'Delete Question': '刪除問題',
    'Delete question confirmation':
        '確定要刪除此問題嗎？\n\n「{question}」\n\n此問題的所有回答也會被刪除。',
    'Single Choice': '單選',
    'Multiple Choice': '多選',
    'Short Text': '短文字',
    'Long Text': '長文字',
    'Visible when {count} rule matches': '當 {count} 條規則符合時顯示',
    'Visible when {count} rules match': '當 {count} 條規則符合時顯示',
    'Edit question': '編輯問題',
    'Delete question': '刪除問題',
    'Placeholder: {placeholder}': '預留文字：{placeholder}',
    'min {value}': '最小 {value}',
    'max {value}': '最大 {value}',
    'Length: {summary}': '長度：{summary}',
    'Selections: {summary}': '選擇數：{summary}',
    'Edit Question': '編輯問題',
    'Question text': '問題文字',
    'Enter your question': '輸入你的問題',
    'Question text is required': '問題文字為必填',
    'Question Type': '問題類型',
    'Placeholder (optional)': '預留文字（選填）',
    'Placeholder text for the input': '輸入欄的預留文字',
    'Min length': '最小長度',
    'Max length': '最大長度',
    'Min selections': '最少選擇數',
    'Max selections': '最多選擇數',
    'Visibility rule match': '可見性規則符合',
    'All rules': '所有規則',
    'Any rule': '任一規則',
    'Required': '必填',
    'Respondents must answer this question': '回答者必須回答此問題',
    'Save': '儲存',
    'Add': '新增',
    'Use 0 or more': '請輸入0或更大的數',
    'Add Choice': '新增選項',
    'Add at least one choice for choice questions': '選擇題至少需要新增一個選項',
    'Choice text': '選項文字',
    'Choice text is required': '選項文字為必填',
    'Visibility rules': '可見性規則',
    'Always visible': '一律顯示',
    '{count} rule': '{count} 條規則',
    '{count} rules': '{count} 條規則',
    'Add an earlier question before creating rules.': '請先新增前置問題，再建立規則。',
    'All': '全部',
    'Any': '任一',
    'Add rule': '新增規則',
    'Save rules': '儲存規則',
    'Question': '問題',
    'Condition': '條件',
    'Delete rule': '刪除規則',
    'Value': '值',
    'equals': '等於',
    'does not equal': '不等於',
    'contains': '包含',
    'does not contain': '不包含',
    'is answered': '已回答',
    'is not answered': '未回答',
    'Generate with AI': '用 AI 生成',
    'Describe your survey and AI will generate questions for you.':
        '描述你的問卷，AI 會為你生成問題。',
    'Example: Onboarding survey for a fitness app asking about exercise experience, target weight, and weekly workout frequency':
        '範例：健身 App 的新使用者問卷，詢問運動經驗、目標體重和每週運動頻率',
    'Generating...': '生成中...',
    'Generate': '生成',
    'Add manually': '手動新增',
    'Generated Questions': '生成的問題',
    '{count} questions generated. Review and apply to your survey.':
        '已生成 {count} 個問題。請檢查並套用到問卷。',
    'Apply': '套用',
    'Choices': '選項',
    'No choices yet. Add at least one choice.': '尚無選項。請至少新增一個選項。',
    'Choice 1': '選項 1',
    'Choice 2': '選項 2',
    'Add User': '新增使用者',
    'Back': '返回',
    'No users yet': '尚無使用者',
    'Add your first user to get started': '新增第一位使用者即可開始',
    'Delete Your Account': '刪除你的帳戶',
    'Delete User': '刪除使用者',
    'Delete your account confirmation': '你即將刪除目前登入的帳戶。刪除後你會立即登出。\n\n確定要繼續嗎？',
    'Delete user confirmation': '確定要刪除 {email} 嗎？',
    'Create User': '建立使用者',
    'Please enter a valid email': '請輸入有效的電子郵件',
    'Password is required': '密碼為必填',
    'Role': '角色',
    'Viewer': '檢視者',
    'Editor': '編輯者',
    'Admin': '管理員',
    'Create': '建立',
    'Can manage users, surveys, responses, and settings.': '可以管理使用者、問卷、回答和設定。',
    'Can create surveys and manage responses.': '可以建立問卷並管理回答。',
    'Can view surveys and responses only.': '只能檢視問卷和回答。',
    'No email': '沒有電子郵件',
    'You': '你',
    'Blocked': '已封鎖',
    'Make admin': '設為管理員',
    'Make editor': '設為編輯者',
    'Make viewer': '設為檢視者',
    'Unblock': '解除封鎖',
    'Block': '封鎖',
    'Invalid email or password': '電子郵件或密碼無效',
    'Too many login attempts. Please try again later.': '登入嘗試次數過多。請稍後再試。',
    'Login failed. Please try again.': '登入失敗。請重試。',
    'Invalid state. Please start over.': '狀態無效。請重新開始。',
    'Password reset successful! You can now login.': '密碼重設成功！現在可以登入。',
    'Password reset is not available. Please contact an administrator.':
        '密碼重設不可用。請聯絡管理員。',
    'Invalid verification code. Please try again.': '驗證碼無效。請重試。',
    'The verification code has expired. Please request a new one.':
        '驗證碼已過期。請要求新的驗證碼。',
    'Too many attempts. Please try again later.': '嘗試次數過多。請稍後再試。',
    'An error occurred. Please try again.': '發生錯誤。請重試。',
    'Settings saved successfully': '設定已儲存',
    'Notifications enabled': '通知已啟用',
    'Notifications disabled': '通知已停用',
    'Test notification sent': '測試通知已傳送',
    'File downloads are only available on web.': '檔案下載僅可在 Web 使用。',
    'Registration failed: ': '註冊失敗：{error}',
    'Failed to load config: ': '載入設定失敗：{error}',
    'Failed to load surveys: ': '載入問卷失敗：{error}',
    'Failed to delete survey: ': '刪除問卷失敗：{error}',
    'Failed to publish survey: ': '發布問卷失敗：{error}',
    'Failed to close survey: ': '關閉問卷失敗：{error}',
    'Failed to reopen survey: ': '重新開啟問卷失敗：{error}',
    'Failed to load survey: ': '載入問卷失敗：{error}',
    'Failed to load questions: ': '載入問題失敗：{error}',
    'Failed to create question: ': '建立問題失敗：{error}',
    'Failed to update question: ': '更新問題失敗：{error}',
    'Failed to delete question: ': '刪除問題失敗：{error}',
    'Failed to reorder questions: ': '重新排序問題失敗：{error}',
    'Failed to create choice: ': '建立選項失敗：{error}',
    'Failed to update choice: ': '更新選項失敗：{error}',
    'Failed to delete choice: ': '刪除選項失敗：{error}',
    'Failed to save visibility rules: ': '儲存可見性規則失敗：{error}',
    'Failed to create survey: ': '建立問卷失敗：{error}',
    'Failed to update survey: ': '更新問卷失敗：{error}',
    'Failed to generate questions: ': '生成問題失敗：{error}',
    'Failed to load results: ': '載入結果失敗：{error}',
    'Failed to load responses: ': '載入回答失敗：{error}',
    'Failed to export responses: ': '匯出回答失敗：{error}',
    'Failed to delete response: ': '刪除回答失敗：{error}',
    'Failed to send reply: ': '傳送回覆失敗：{error}',
    'Failed to load notification settings: ': '載入通知設定失敗：{error}',
    'Failed to save settings: ': '儲存設定失敗：{error}',
    'Failed to toggle notifications: ': '切換通知失敗：{error}',
    'Failed to send test notification: ': '傳送測試通知失敗：{error}',
    'Failed to load users: ': '載入使用者失敗：{error}',
    'Failed to create user: ': '建立使用者失敗：{error}',
    'Failed to update role: ': '更新角色失敗：{error}',
    'Failed to delete user: ': '刪除使用者失敗：{error}',
    'Failed to update user: ': '更新使用者失敗：{error}',
  },
  'ko': {
    'Form Concierge Admin': 'Form Concierge Admin',
    'Form Concierge': 'Form Concierge',
    'Admin Dashboard': '관리자 대시보드',
    'Welcome! Create your admin account to get started.':
        '환영합니다! 시작하려면 관리자 계정을 만드세요.',
    'Email': '이메일',
    'Password': '비밀번호',
    'Forgot Password?': '비밀번호를 잊으셨나요?',
    'Create Account': '계정 만들기',
    'Login': '로그인',
    'Forgot Password': '비밀번호 재설정',
    'Reset Your Password': '비밀번호 재설정',
    "Enter your email address and we'll send you a verification code.":
        '이메일 주소를 입력하면 인증 코드를 보내드립니다.',
    'Send Code': '코드 보내기',
    'Back to Login': '로그인으로 돌아가기',
    'Verify Code': '코드 확인',
    'Check Your Email': '이메일을 확인하세요',
    'We sent a verification code to:': '인증 코드를 보낸 주소:',
    'Verification Code': '인증 코드',
    'Enter 6-digit code': '6자리 코드 입력',
    'Verify': '확인',
    'Cancel': '취소',
    'Password Reset Complete': '비밀번호 재설정 완료',
    'Your password has been successfully reset. You can now login with your new password.':
        '비밀번호가 재설정되었습니다. 새 비밀번호로 로그인할 수 있습니다.',
    'Go to Login': '로그인으로 이동',
    'New Password': '새 비밀번호',
    'Create New Password': '새 비밀번호 만들기',
    'Enter a new password for your account.': '계정의 새 비밀번호를 입력하세요.',
    'Confirm Password': '비밀번호 확인',
    'Reset Password': '비밀번호 재설정',
    'Please enter a password': '비밀번호를 입력하세요',
    'Password must be at least 8 characters': '비밀번호는 8자 이상이어야 합니다',
    'Passwords do not match': '비밀번호가 일치하지 않습니다',
    'Surveys': '설문',
    'Refresh': '새로고침',
    'User Management': '사용자 관리',
    'Logout': '로그아웃',
    'New Survey': '새 설문',
    'Retry': '다시 시도',
    'No surveys yet': '아직 설문이 없습니다',
    'Create your first survey to get started': '첫 설문을 만들어 시작하세요',
    'Create Survey': '설문 만들기',
    'Delete Survey': '설문 삭제',
    'Delete survey confirmation':
        '"{title}" 설문을 삭제할까요?\n\n모든 질문과 응답도 함께 삭제됩니다. 이 작업은 되돌릴 수 없습니다.',
    'Publish': '게시',
    'Close': '닫기',
    'Reopen': '다시 열기',
    'View Responses': '응답 보기',
    'Delete': '삭제',
    'Draft': '초안',
    'Published': '게시됨',
    'Closed': '닫힘',
    'Archived': '보관됨',
    'Responses': '응답',
    'Export responses': '응답 내보내기',
    'Export CSV': 'CSV 내보내기',
    'Export JSON': 'JSON 내보내기',
    'Results': '결과',
    'Individual': '개별',
    'Notifications': '알림',
    'Delete Response': '응답 삭제',
    'Delete response confirmation': '이 응답을 삭제할까요?\n\n이 작업은 되돌릴 수 없습니다.',
    'Reply to respondent': '응답자에게 답장',
    'Message': '메시지',
    'Send': '보내기',
    'Reply sent': '답장을 보냈습니다',
    'Exported {filename}': '{filename} 내보냄',
    'No responses yet': '아직 응답이 없습니다',
    'Share your survey to start collecting responses': '응답을 수집하려면 설문을 공유하세요',
    'Total Responses': '총 응답 수',
    'Results by Question': '질문별 결과',
    'Choice': '선택지',
    'Count': '수',
    'No text responses': '텍스트 응답이 없습니다',
    '{count} response': '응답 {count}개',
    '{count} responses': '응답 {count}개',
    '... and {count} more responses': '... 외 응답 {count}개',
    'Previous page': '이전 페이지',
    'Next page': '다음 페이지',
    'Page {currentPage} of {totalPages}': '{totalPages}페이지 중 {currentPage}페이지',
    'User #{id}': '사용자 #{id}',
    'Anonymous': '익명',
    'Reply': '답장',
    'Delete response': '응답 삭제',
    'Email service is not configured. Contact your administrator to enable SMTP settings.':
        '이메일 서비스가 설정되지 않았습니다. SMTP 설정을 활성화하려면 관리자에게 문의하세요.',
    'Daily Email Notifications': '일일 이메일 알림',
    'Receive a daily summary of new survey responses via email.':
        '새 설문 응답의 일일 요약을 이메일로 받습니다.',
    'Recipient Email': '수신자 이메일',
    'Email is required': '이메일은 필수입니다',
    'Enter a valid email address': '유효한 이메일 주소를 입력하세요',
    'Send Time (UTC)': '발송 시간 (UTC)',
    'Create Settings': '설정 만들기',
    'Save Changes': '변경 사항 저장',
    'Enable Notifications': '알림 활성화',
    'Daily notifications are active': '일일 알림이 활성화되었습니다',
    'Daily notifications are paused': '일일 알림이 일시 중지되었습니다',
    'Last Sent': '마지막 발송',
    'Send Test Notification': '테스트 알림 보내기',
    'Loading...': '로딩 중...',
    'Survey Not Found': '설문을 찾을 수 없음',
    'Survey not found': '설문을 찾을 수 없습니다',
    'Back to Dashboard': '대시보드로 돌아가기',
    'This survey is archived. You cannot edit the questions.':
        '이 설문은 보관되었습니다. 질문을 편집할 수 없습니다.',
    'Publish Survey': '설문 게시',
    'Publish survey confirmation': '이 설문을 게시할까요?\n\n게시 후에는 질문을 편집할 수 없습니다.',
    'Title': '제목',
    'Enter survey title': '설문 제목 입력',
    'Title is required': '제목은 필수입니다',
    'Other languages': '다른 언어',
    'URL Slug': 'URL 슬러그',
    'Slug is required': '슬러그는 필수입니다',
    'Only lowercase letters, numbers, and hyphens allowed':
        '소문자, 숫자, 하이픈만 사용할 수 있습니다',
    'Description (optional)': '설명(선택 사항)',
    'Brief description of the survey': '설문에 대한 간단한 설명',
    'Questions': '질문',
    'No questions yet': '아직 질문이 없습니다',
    'Add questions to your survey': '설문에 질문을 추가하세요',
    'Add Question': '질문 추가',
    'Delete Question': '질문 삭제',
    'Delete question confirmation':
        '이 질문을 삭제할까요?\n\n"{question}"\n\n이 질문의 모든 응답도 삭제됩니다.',
    'Single Choice': '단일 선택',
    'Multiple Choice': '복수 선택',
    'Short Text': '짧은 텍스트',
    'Long Text': '긴 텍스트',
    'Visible when {count} rule matches': '규칙 {count}개가 일치하면 표시',
    'Visible when {count} rules match': '규칙 {count}개가 일치하면 표시',
    'Edit question': '질문 편집',
    'Delete question': '질문 삭제',
    'Placeholder: {placeholder}': '플레이스홀더: {placeholder}',
    'min {value}': '최소 {value}',
    'max {value}': '최대 {value}',
    'Length: {summary}': '길이: {summary}',
    'Selections: {summary}': '선택 수: {summary}',
    'Edit Question': '질문 편집',
    'Question text': '질문 문구',
    'Enter your question': '질문을 입력하세요',
    'Question text is required': '질문 문구는 필수입니다',
    'Question Type': '질문 유형',
    'Placeholder (optional)': '플레이스홀더(선택 사항)',
    'Placeholder text for the input': '입력란 플레이스홀더 텍스트',
    'Min length': '최소 길이',
    'Max length': '최대 길이',
    'Min selections': '최소 선택 수',
    'Max selections': '최대 선택 수',
    'Visibility rule match': '표시 규칙 일치 조건',
    'All rules': '모든 규칙',
    'Any rule': '규칙 중 하나',
    'Required': '필수',
    'Respondents must answer this question': '응답자는 이 질문에 답해야 합니다',
    'Save': '저장',
    'Add': '추가',
    'Use 0 or more': '0 이상의 값을 입력하세요',
    'Add Choice': '선택지 추가',
    'Add at least one choice for choice questions': '선택형 질문에는 선택지를 하나 이상 추가하세요',
    'Choice text': '선택지 텍스트',
    'Choice text is required': '선택지 텍스트는 필수입니다',
    'Visibility rules': '표시 규칙',
    'Always visible': '항상 표시',
    '{count} rule': '규칙 {count}개',
    '{count} rules': '규칙 {count}개',
    'Add an earlier question before creating rules.':
        '규칙을 만들기 전에 앞선 질문을 추가하세요.',
    'All': '모두',
    'Any': '하나 이상',
    'Add rule': '규칙 추가',
    'Save rules': '규칙 저장',
    'Question': '질문',
    'Condition': '조건',
    'Delete rule': '규칙 삭제',
    'Value': '값',
    'equals': '같음',
    'does not equal': '같지 않음',
    'contains': '포함',
    'does not contain': '포함하지 않음',
    'is answered': '답변됨',
    'is not answered': '답변되지 않음',
    'Generate with AI': 'AI로 생성',
    'Describe your survey and AI will generate questions for you.':
        '설문을 설명하면 AI가 질문을 생성합니다.',
    'Example: Onboarding survey for a fitness app asking about exercise experience, target weight, and weekly workout frequency':
        '예: 운동 경험, 목표 체중, 주간 운동 빈도를 묻는 피트니스 앱 온보딩 설문',
    'Generating...': '생성 중...',
    'Generate': '생성',
    'Add manually': '수동 추가',
    'Generated Questions': '생성된 질문',
    '{count} questions generated. Review and apply to your survey.':
        '질문 {count}개가 생성되었습니다. 검토 후 설문에 적용하세요.',
    'Apply': '적용',
    'Choices': '선택지',
    'No choices yet. Add at least one choice.':
        '아직 선택지가 없습니다. 선택지를 하나 이상 추가하세요.',
    'Choice 1': '선택지 1',
    'Choice 2': '선택지 2',
    'Add User': '사용자 추가',
    'Back': '뒤로',
    'No users yet': '아직 사용자가 없습니다',
    'Add your first user to get started': '첫 사용자를 추가해 시작하세요',
    'Delete Your Account': '내 계정 삭제',
    'Delete User': '사용자 삭제',
    'Delete your account confirmation':
        '현재 로그인한 계정을 삭제하려고 합니다. 삭제 후 즉시 로그아웃됩니다.\n\n계속할까요?',
    'Delete user confirmation': '{email} 사용자를 삭제할까요?',
    'Create User': '사용자 만들기',
    'Please enter a valid email': '유효한 이메일을 입력하세요',
    'Password is required': '비밀번호는 필수입니다',
    'Role': '역할',
    'Viewer': '뷰어',
    'Editor': '편집자',
    'Admin': '관리자',
    'Create': '만들기',
    'Can manage users, surveys, responses, and settings.':
        '사용자, 설문, 응답, 설정을 관리할 수 있습니다.',
    'Can create surveys and manage responses.': '설문을 만들고 응답을 관리할 수 있습니다.',
    'Can view surveys and responses only.': '설문과 응답만 볼 수 있습니다.',
    'No email': '이메일 없음',
    'You': '나',
    'Blocked': '차단됨',
    'Make admin': '관리자로 변경',
    'Make editor': '편집자로 변경',
    'Make viewer': '뷰어로 변경',
    'Unblock': '차단 해제',
    'Block': '차단',
    'Invalid email or password': '이메일 또는 비밀번호가 올바르지 않습니다',
    'Too many login attempts. Please try again later.':
        '로그인 시도가 너무 많습니다. 나중에 다시 시도하세요.',
    'Login failed. Please try again.': '로그인에 실패했습니다. 다시 시도하세요.',
    'Invalid state. Please start over.': '상태가 올바르지 않습니다. 처음부터 다시 시작하세요.',
    'Password reset successful! You can now login.':
        '비밀번호가 재설정되었습니다! 이제 로그인할 수 있습니다.',
    'Password reset is not available. Please contact an administrator.':
        '비밀번호 재설정을 사용할 수 없습니다. 관리자에게 문의하세요.',
    'Invalid verification code. Please try again.':
        '인증 코드가 올바르지 않습니다. 다시 시도하세요.',
    'The verification code has expired. Please request a new one.':
        '인증 코드가 만료되었습니다. 새 코드를 요청하세요.',
    'Too many attempts. Please try again later.': '시도가 너무 많습니다. 나중에 다시 시도하세요.',
    'An error occurred. Please try again.': '오류가 발생했습니다. 다시 시도하세요.',
    'Settings saved successfully': '설정이 저장되었습니다',
    'Notifications enabled': '알림이 활성화되었습니다',
    'Notifications disabled': '알림이 비활성화되었습니다',
    'Test notification sent': '테스트 알림을 보냈습니다',
    'File downloads are only available on web.': '파일 다운로드는 웹에서만 사용할 수 있습니다.',
    'Registration failed: ': '등록 실패: {error}',
    'Failed to load config: ': '설정을 불러오지 못했습니다: {error}',
    'Failed to load surveys: ': '설문을 불러오지 못했습니다: {error}',
    'Failed to delete survey: ': '설문을 삭제하지 못했습니다: {error}',
    'Failed to publish survey: ': '설문을 게시하지 못했습니다: {error}',
    'Failed to close survey: ': '설문을 닫지 못했습니다: {error}',
    'Failed to reopen survey: ': '설문을 다시 열지 못했습니다: {error}',
    'Failed to load survey: ': '설문을 불러오지 못했습니다: {error}',
    'Failed to load questions: ': '질문을 불러오지 못했습니다: {error}',
    'Failed to create question: ': '질문을 만들지 못했습니다: {error}',
    'Failed to update question: ': '질문을 업데이트하지 못했습니다: {error}',
    'Failed to delete question: ': '질문을 삭제하지 못했습니다: {error}',
    'Failed to reorder questions: ': '질문 순서를 바꾸지 못했습니다: {error}',
    'Failed to create choice: ': '선택지를 만들지 못했습니다: {error}',
    'Failed to update choice: ': '선택지를 업데이트하지 못했습니다: {error}',
    'Failed to delete choice: ': '선택지를 삭제하지 못했습니다: {error}',
    'Failed to save visibility rules: ': '표시 규칙을 저장하지 못했습니다: {error}',
    'Failed to create survey: ': '설문을 만들지 못했습니다: {error}',
    'Failed to update survey: ': '설문을 업데이트하지 못했습니다: {error}',
    'Failed to generate questions: ': '질문을 생성하지 못했습니다: {error}',
    'Failed to load results: ': '결과를 불러오지 못했습니다: {error}',
    'Failed to load responses: ': '응답을 불러오지 못했습니다: {error}',
    'Failed to export responses: ': '응답을 내보내지 못했습니다: {error}',
    'Failed to delete response: ': '응답을 삭제하지 못했습니다: {error}',
    'Failed to send reply: ': '답장을 보내지 못했습니다: {error}',
    'Failed to load notification settings: ': '알림 설정을 불러오지 못했습니다: {error}',
    'Failed to save settings: ': '설정을 저장하지 못했습니다: {error}',
    'Failed to toggle notifications: ': '알림을 전환하지 못했습니다: {error}',
    'Failed to send test notification: ': '테스트 알림을 보내지 못했습니다: {error}',
    'Failed to load users: ': '사용자를 불러오지 못했습니다: {error}',
    'Failed to create user: ': '사용자를 만들지 못했습니다: {error}',
    'Failed to update role: ': '역할을 업데이트하지 못했습니다: {error}',
    'Failed to delete user: ': '사용자를 삭제하지 못했습니다: {error}',
    'Failed to update user: ': '사용자를 업데이트하지 못했습니다: {error}',
  },
  'de': {
    'Form Concierge Admin': 'Form Concierge Admin',
    'Form Concierge': 'Form Concierge',
    'Admin Dashboard': 'Admin-Dashboard',
    'Welcome! Create your admin account to get started.':
        'Willkommen! Erstelle ein Administratorkonto, um zu beginnen.',
    'Email': 'E-Mail',
    'Password': 'Passwort',
    'Forgot Password?': 'Passwort vergessen?',
    'Create Account': 'Konto erstellen',
    'Login': 'Anmelden',
    'Forgot Password': 'Passwort vergessen',
    'Reset Your Password': 'Passwort zurücksetzen',
    "Enter your email address and we'll send you a verification code.":
        'Gib deine E-Mail-Adresse ein. Wir senden dir einen Bestätigungscode.',
    'Send Code': 'Code senden',
    'Back to Login': 'Zur Anmeldung',
    'Verify Code': 'Code bestätigen',
    'Check Your Email': 'E-Mail prüfen',
    'We sent a verification code to:':
        'Wir haben einen Bestätigungscode gesendet an:',
    'Verification Code': 'Bestätigungscode',
    'Enter 6-digit code': '6-stelligen Code eingeben',
    'Verify': 'Bestätigen',
    'Cancel': 'Abbrechen',
    'Password Reset Complete': 'Passwort zurückgesetzt',
    'Your password has been successfully reset. You can now login with your new password.':
        'Dein Passwort wurde zurückgesetzt. Du kannst dich jetzt mit dem neuen Passwort anmelden.',
    'Go to Login': 'Zur Anmeldung',
    'New Password': 'Neues Passwort',
    'Create New Password': 'Neues Passwort erstellen',
    'Enter a new password for your account.':
        'Gib ein neues Passwort für dein Konto ein.',
    'Confirm Password': 'Passwort bestätigen',
    'Reset Password': 'Passwort zurücksetzen',
    'Please enter a password': 'Bitte Passwort eingeben',
    'Password must be at least 8 characters':
        'Das Passwort muss mindestens 8 Zeichen lang sein',
    'Passwords do not match': 'Passwörter stimmen nicht überein',
    'Surveys': 'Umfragen',
    'Refresh': 'Aktualisieren',
    'User Management': 'Benutzerverwaltung',
    'Logout': 'Abmelden',
    'New Survey': 'Neue Umfrage',
    'Retry': 'Erneut versuchen',
    'No surveys yet': 'Noch keine Umfragen',
    'Create your first survey to get started':
        'Erstelle deine erste Umfrage, um zu beginnen',
    'Create Survey': 'Umfrage erstellen',
    'Delete Survey': 'Umfrage löschen',
    'Delete survey confirmation':
        'Möchtest du "{title}" wirklich löschen?\n\nDadurch werden auch alle Fragen und Antworten gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    'Publish': 'Veröffentlichen',
    'Close': 'Schließen',
    'Reopen': 'Wieder öffnen',
    'View Responses': 'Antworten ansehen',
    'Delete': 'Löschen',
    'Draft': 'Entwurf',
    'Published': 'Veröffentlicht',
    'Closed': 'Geschlossen',
    'Archived': 'Archiviert',
    'Responses': 'Antworten',
    'Export responses': 'Antworten exportieren',
    'Export CSV': 'CSV exportieren',
    'Export JSON': 'JSON exportieren',
    'Results': 'Ergebnisse',
    'Individual': 'Einzeln',
    'Notifications': 'Benachrichtigungen',
    'Delete Response': 'Antwort löschen',
    'Delete response confirmation':
        'Möchtest du diese Antwort wirklich löschen?\n\nDiese Aktion kann nicht rückgängig gemacht werden.',
    'Reply to respondent': 'An Befragten antworten',
    'Message': 'Nachricht',
    'Send': 'Senden',
    'Reply sent': 'Antwort gesendet',
    'Exported {filename}': '{filename} exportiert',
    'No responses yet': 'Noch keine Antworten',
    'Share your survey to start collecting responses':
        'Teile deine Umfrage, um Antworten zu sammeln',
    'Total Responses': 'Antworten gesamt',
    'Results by Question': 'Ergebnisse nach Frage',
    'Choice': 'Auswahl',
    'Count': 'Anzahl',
    'No text responses': 'Keine Textantworten',
    '{count} response': '{count} Antwort',
    '{count} responses': '{count} Antworten',
    '... and {count} more responses': '... und {count} weitere Antworten',
    'Previous page': 'Vorherige Seite',
    'Next page': 'Nächste Seite',
    'Page {currentPage} of {totalPages}':
        'Seite {currentPage} von {totalPages}',
    'User #{id}': 'Benutzer #{id}',
    'Anonymous': 'Anonym',
    'Reply': 'Antworten',
    'Delete response': 'Antwort löschen',
    'Email service is not configured. Contact your administrator to enable SMTP settings.':
        'Der E-Mail-Dienst ist nicht konfiguriert. Kontaktiere den Administrator, um SMTP zu aktivieren.',
    'Daily Email Notifications': 'Tägliche E-Mail-Benachrichtigungen',
    'Receive a daily summary of new survey responses via email.':
        'Erhalte täglich eine Zusammenfassung neuer Umfrageantworten per E-Mail.',
    'Recipient Email': 'Empfänger-E-Mail',
    'Email is required': 'E-Mail ist erforderlich',
    'Enter a valid email address': 'Gib eine gültige E-Mail-Adresse ein',
    'Send Time (UTC)': 'Sendezeit (UTC)',
    'Create Settings': 'Einstellungen erstellen',
    'Save Changes': 'Änderungen speichern',
    'Enable Notifications': 'Benachrichtigungen aktivieren',
    'Daily notifications are active': 'Tägliche Benachrichtigungen sind aktiv',
    'Daily notifications are paused':
        'Tägliche Benachrichtigungen sind pausiert',
    'Last Sent': 'Zuletzt gesendet',
    'Send Test Notification': 'Testbenachrichtigung senden',
    'Loading...': 'Wird geladen...',
    'Survey Not Found': 'Umfrage nicht gefunden',
    'Survey not found': 'Umfrage nicht gefunden',
    'Back to Dashboard': 'Zurück zum Dashboard',
    'This survey is archived. You cannot edit the questions.':
        'Diese Umfrage ist archiviert. Du kannst die Fragen nicht bearbeiten.',
    'Publish Survey': 'Umfrage veröffentlichen',
    'Publish survey confirmation':
        'Möchtest du diese Umfrage wirklich veröffentlichen?\n\nNach der Veröffentlichung kannst du die Fragen nicht mehr bearbeiten.',
    'Title': 'Titel',
    'Enter survey title': 'Umfragetitel eingeben',
    'Title is required': 'Titel ist erforderlich',
    'Other languages': 'Andere Sprachen',
    'URL Slug': 'URL-Slug',
    'Slug is required': 'Slug ist erforderlich',
    'Only lowercase letters, numbers, and hyphens allowed':
        'Nur Kleinbuchstaben, Zahlen und Bindestriche sind erlaubt',
    'Description (optional)': 'Beschreibung (optional)',
    'Brief description of the survey': 'Kurze Beschreibung der Umfrage',
    'Questions': 'Fragen',
    'No questions yet': 'Noch keine Fragen',
    'Add questions to your survey': 'Füge deiner Umfrage Fragen hinzu',
    'Add Question': 'Frage hinzufügen',
    'Delete Question': 'Frage löschen',
    'Delete question confirmation':
        'Möchtest du diese Frage wirklich löschen?\n\n"{question}"\n\nDadurch werden auch alle Antworten auf diese Frage gelöscht.',
    'Single Choice': 'Einzelauswahl',
    'Multiple Choice': 'Mehrfachauswahl',
    'Short Text': 'Kurztext',
    'Long Text': 'Langtext',
    'Visible when {count} rule matches':
        'Sichtbar, wenn {count} Regel übereinstimmt',
    'Visible when {count} rules match':
        'Sichtbar, wenn {count} Regeln übereinstimmen',
    'Edit question': 'Frage bearbeiten',
    'Delete question': 'Frage löschen',
    'Placeholder: {placeholder}': 'Platzhalter: {placeholder}',
    'min {value}': 'min. {value}',
    'max {value}': 'max. {value}',
    'Length: {summary}': 'Länge: {summary}',
    'Selections: {summary}': 'Auswahlen: {summary}',
    'Edit Question': 'Frage bearbeiten',
    'Question text': 'Fragetext',
    'Enter your question': 'Frage eingeben',
    'Question text is required': 'Fragetext ist erforderlich',
    'Question Type': 'Fragetyp',
    'Placeholder (optional)': 'Platzhalter (optional)',
    'Placeholder text for the input': 'Platzhaltertext für die Eingabe',
    'Min length': 'Mindestlänge',
    'Max length': 'Maximallänge',
    'Min selections': 'Min. Auswahlen',
    'Max selections': 'Max. Auswahlen',
    'Visibility rule match': 'Übereinstimmung der Sichtbarkeitsregeln',
    'All rules': 'Alle Regeln',
    'Any rule': 'Eine Regel',
    'Required': 'Erforderlich',
    'Respondents must answer this question':
        'Befragte müssen diese Frage beantworten',
    'Save': 'Speichern',
    'Add': 'Hinzufügen',
    'Use 0 or more': '0 oder mehr verwenden',
    'Add Choice': 'Auswahl hinzufügen',
    'Add at least one choice for choice questions':
        'Füge bei Auswahlfragen mindestens eine Auswahl hinzu',
    'Choice text': 'Auswahltext',
    'Choice text is required': 'Auswahltext ist erforderlich',
    'Visibility rules': 'Sichtbarkeitsregeln',
    'Always visible': 'Immer sichtbar',
    '{count} rule': '{count} Regel',
    '{count} rules': '{count} Regeln',
    'Add an earlier question before creating rules.':
        'Füge eine frühere Frage hinzu, bevor du Regeln erstellst.',
    'All': 'Alle',
    'Any': 'Eine',
    'Add rule': 'Regel hinzufügen',
    'Save rules': 'Regeln speichern',
    'Question': 'Frage',
    'Condition': 'Bedingung',
    'Delete rule': 'Regel löschen',
    'Value': 'Wert',
    'equals': 'ist gleich',
    'does not equal': 'ist nicht gleich',
    'contains': 'enthält',
    'does not contain': 'enthält nicht',
    'is answered': 'ist beantwortet',
    'is not answered': 'ist nicht beantwortet',
    'Generate with AI': 'Mit KI generieren',
    'Describe your survey and AI will generate questions for you.':
        'Beschreibe deine Umfrage. Die KI generiert Fragen für dich.',
    'Example: Onboarding survey for a fitness app asking about exercise experience, target weight, and weekly workout frequency':
        'Beispiel: Onboarding-Umfrage für eine Fitness-App mit Fragen zu Trainingserfahrung, Zielgewicht und wöchentlicher Trainingshäufigkeit',
    'Generating...': 'Wird generiert...',
    'Generate': 'Generieren',
    'Add manually': 'Manuell hinzufügen',
    'Generated Questions': 'Generierte Fragen',
    '{count} questions generated. Review and apply to your survey.':
        '{count} Fragen wurden generiert. Prüfe sie und übernimm sie in deine Umfrage.',
    'Apply': 'Anwenden',
    'Choices': 'Auswahlen',
    'No choices yet. Add at least one choice.':
        'Noch keine Auswahlen. Füge mindestens eine Auswahl hinzu.',
    'Choice 1': 'Auswahl 1',
    'Choice 2': 'Auswahl 2',
    'Add User': 'Benutzer hinzufügen',
    'Back': 'Zurück',
    'No users yet': 'Noch keine Benutzer',
    'Add your first user to get started':
        'Füge deinen ersten Benutzer hinzu, um zu beginnen',
    'Delete Your Account': 'Eigenes Konto löschen',
    'Delete User': 'Benutzer löschen',
    'Delete your account confirmation':
        'Du bist dabei, dein aktuell angemeldetes Konto zu löschen. Nach dem Löschen wirst du sofort abgemeldet.\n\nMöchtest du fortfahren?',
    'Delete user confirmation': 'Möchtest du {email} wirklich löschen?',
    'Create User': 'Benutzer erstellen',
    'Please enter a valid email': 'Bitte gültige E-Mail eingeben',
    'Password is required': 'Passwort ist erforderlich',
    'Role': 'Rolle',
    'Viewer': 'Betrachter',
    'Editor': 'Bearbeiter',
    'Admin': 'Administrator',
    'Create': 'Erstellen',
    'Can manage users, surveys, responses, and settings.':
        'Kann Benutzer, Umfragen, Antworten und Einstellungen verwalten.',
    'Can create surveys and manage responses.':
        'Kann Umfragen erstellen und Antworten verwalten.',
    'Can view surveys and responses only.':
        'Kann nur Umfragen und Antworten ansehen.',
    'No email': 'Keine E-Mail',
    'You': 'Du',
    'Blocked': 'Blockiert',
    'Make admin': 'Zum Administrator machen',
    'Make editor': 'Zum Bearbeiter machen',
    'Make viewer': 'Zum Betrachter machen',
    'Unblock': 'Entsperren',
    'Block': 'Blockieren',
    'Invalid email or password': 'E-Mail oder Passwort ist ungültig',
    'Too many login attempts. Please try again later.':
        'Zu viele Anmeldeversuche. Bitte später erneut versuchen.',
    'Login failed. Please try again.':
        'Anmeldung fehlgeschlagen. Bitte erneut versuchen.',
    'Invalid state. Please start over.':
        'Ungültiger Zustand. Bitte von vorn beginnen.',
    'Password reset successful! You can now login.':
        'Passwort wurde zurückgesetzt. Du kannst dich jetzt anmelden.',
    'Password reset is not available. Please contact an administrator.':
        'Passwort-Zurücksetzen ist nicht verfügbar. Bitte kontaktiere einen Administrator.',
    'Invalid verification code. Please try again.':
        'Ungültiger Bestätigungscode. Bitte erneut versuchen.',
    'The verification code has expired. Please request a new one.':
        'Der Bestätigungscode ist abgelaufen. Bitte fordere einen neuen an.',
    'Too many attempts. Please try again later.':
        'Zu viele Versuche. Bitte später erneut versuchen.',
    'An error occurred. Please try again.':
        'Ein Fehler ist aufgetreten. Bitte erneut versuchen.',
    'Settings saved successfully': 'Einstellungen gespeichert',
    'Notifications enabled': 'Benachrichtigungen aktiviert',
    'Notifications disabled': 'Benachrichtigungen deaktiviert',
    'Test notification sent': 'Testbenachrichtigung gesendet',
    'File downloads are only available on web.':
        'Dateidownloads sind nur im Web verfügbar.',
    'Registration failed: ': 'Registrierung fehlgeschlagen: {error}',
    'Failed to load config: ':
        'Konfiguration konnte nicht geladen werden: {error}',
    'Failed to load surveys: ':
        'Umfragen konnten nicht geladen werden: {error}',
    'Failed to delete survey: ':
        'Umfrage konnte nicht gelöscht werden: {error}',
    'Failed to publish survey: ':
        'Umfrage konnte nicht veröffentlicht werden: {error}',
    'Failed to close survey: ':
        'Umfrage konnte nicht geschlossen werden: {error}',
    'Failed to reopen survey: ':
        'Umfrage konnte nicht wieder geöffnet werden: {error}',
    'Failed to load survey: ': 'Umfrage konnte nicht geladen werden: {error}',
    'Failed to load questions: ':
        'Fragen konnten nicht geladen werden: {error}',
    'Failed to create question: ':
        'Frage konnte nicht erstellt werden: {error}',
    'Failed to update question: ':
        'Frage konnte nicht aktualisiert werden: {error}',
    'Failed to delete question: ':
        'Frage konnte nicht gelöscht werden: {error}',
    'Failed to reorder questions: ':
        'Fragen konnten nicht sortiert werden: {error}',
    'Failed to create choice: ':
        'Auswahl konnte nicht erstellt werden: {error}',
    'Failed to update choice: ':
        'Auswahl konnte nicht aktualisiert werden: {error}',
    'Failed to delete choice: ':
        'Auswahl konnte nicht gelöscht werden: {error}',
    'Failed to save visibility rules: ':
        'Sichtbarkeitsregeln konnten nicht gespeichert werden: {error}',
    'Failed to create survey: ':
        'Umfrage konnte nicht erstellt werden: {error}',
    'Failed to update survey: ':
        'Umfrage konnte nicht aktualisiert werden: {error}',
    'Failed to generate questions: ':
        'Fragen konnten nicht generiert werden: {error}',
    'Failed to load results: ':
        'Ergebnisse konnten nicht geladen werden: {error}',
    'Failed to load responses: ':
        'Antworten konnten nicht geladen werden: {error}',
    'Failed to export responses: ':
        'Antworten konnten nicht exportiert werden: {error}',
    'Failed to delete response: ':
        'Antwort konnte nicht gelöscht werden: {error}',
    'Failed to send reply: ': 'Antwort konnte nicht gesendet werden: {error}',
    'Failed to load notification settings: ':
        'Benachrichtigungseinstellungen konnten nicht geladen werden: {error}',
    'Failed to save settings: ':
        'Einstellungen konnten nicht gespeichert werden: {error}',
    'Failed to toggle notifications: ':
        'Benachrichtigungen konnten nicht umgeschaltet werden: {error}',
    'Failed to send test notification: ':
        'Testbenachrichtigung konnte nicht gesendet werden: {error}',
    'Failed to load users: ': 'Benutzer konnten nicht geladen werden: {error}',
    'Failed to create user: ': 'Benutzer konnte nicht erstellt werden: {error}',
    'Failed to update role: ':
        'Rolle konnte nicht aktualisiert werden: {error}',
    'Failed to delete user: ': 'Benutzer konnte nicht gelöscht werden: {error}',
    'Failed to update user: ':
        'Benutzer konnte nicht aktualisiert werden: {error}',
  },
};
