/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _i1;
import 'package:serverpod_client/serverpod_client.dart' as _i2;
import 'dart:async' as _i3;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _i4;
import 'package:form_concierge_client/src/protocol/public_config.dart' as _i5;
import 'package:form_concierge_client/src/protocol/question.dart' as _i6;
import 'package:form_concierge_client/src/protocol/question_option.dart' as _i7;
import 'package:form_concierge_client/src/protocol/survey_response.dart' as _i8;
import 'package:form_concierge_client/src/protocol/answer.dart' as _i9;
import 'package:form_concierge_client/src/protocol/survey_results.dart' as _i10;
import 'package:form_concierge_client/src/protocol/survey.dart' as _i11;
import 'package:form_concierge_client/src/protocol/auth_user_info.dart' as _i12;
import 'protocol.dart' as _i13;

/// Endpoint for refreshing JWT tokens
/// {@category Endpoint}
class EndpointRefreshJwtTokens extends _i1.EndpointRefreshJwtTokens {
  EndpointRefreshJwtTokens(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'refreshJwtTokens';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _i3.Future<_i1.AuthSuccess> refreshAccessToken({
    required String refreshToken,
  }) => caller.callServerEndpoint<_i1.AuthSuccess>(
    'refreshJwtTokens',
    'refreshAccessToken',
    {'refreshToken': refreshToken},
    authenticated: false,
  );
}

/// Endpoint for email-based authentication
/// {@category Endpoint}
class EndpointEmailIdp extends _i4.EndpointEmailIdpBase {
  EndpointEmailIdp(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'emailIdp';

  /// Logs in the user and returns a new session.
  ///
  /// Throws an [EmailAccountLoginException] in case of errors, with reason:
  /// - [EmailAccountLoginExceptionReason.invalidCredentials] if the email or
  ///   password is incorrect.
  /// - [EmailAccountLoginExceptionReason.tooManyAttempts] if there have been
  ///   too many failed login attempts.
  ///
  /// Throws an [AuthUserBlockedException] if the auth user is blocked.
  @override
  _i3.Future<_i1.AuthSuccess> login({
    required String email,
    required String password,
  }) => caller.callServerEndpoint<_i1.AuthSuccess>(
    'emailIdp',
    'login',
    {
      'email': email,
      'password': password,
    },
  );

  /// Starts the registration for a new user account with an email-based login
  /// associated to it.
  ///
  /// Upon successful completion of this method, an email will have been
  /// sent to [email] with a verification link, which the user must open to
  /// complete the registration.
  ///
  /// Always returns a account request ID, which can be used to complete the
  /// registration. If the email is already registered, the returned ID will not
  /// be valid.
  @override
  _i3.Future<_i2.UuidValue> startRegistration({required String email}) =>
      caller.callServerEndpoint<_i2.UuidValue>(
        'emailIdp',
        'startRegistration',
        {'email': email},
      );

  /// Verifies an account request code and returns a token
  /// that can be used to complete the account creation.
  ///
  /// Throws an [EmailAccountRequestException] in case of errors, with reason:
  /// - [EmailAccountRequestExceptionReason.expired] if the account request has
  ///   already expired.
  /// - [EmailAccountRequestExceptionReason.policyViolation] if the password
  ///   does not comply with the password policy.
  /// - [EmailAccountRequestExceptionReason.invalid] if no request exists
  ///   for the given [accountRequestId] or [verificationCode] is invalid.
  @override
  _i3.Future<String> verifyRegistrationCode({
    required _i2.UuidValue accountRequestId,
    required String verificationCode,
  }) => caller.callServerEndpoint<String>(
    'emailIdp',
    'verifyRegistrationCode',
    {
      'accountRequestId': accountRequestId,
      'verificationCode': verificationCode,
    },
  );

  /// Completes a new account registration, creating a new auth user with a
  /// profile and attaching the given email account to it.
  ///
  /// Throws an [EmailAccountRequestException] in case of errors, with reason:
  /// - [EmailAccountRequestExceptionReason.expired] if the account request has
  ///   already expired.
  /// - [EmailAccountRequestExceptionReason.policyViolation] if the password
  ///   does not comply with the password policy.
  /// - [EmailAccountRequestExceptionReason.invalid] if the [registrationToken]
  ///   is invalid.
  ///
  /// Throws an [AuthUserBlockedException] if the auth user is blocked.
  ///
  /// Returns a session for the newly created user.
  @override
  _i3.Future<_i1.AuthSuccess> finishRegistration({
    required String registrationToken,
    required String password,
  }) => caller.callServerEndpoint<_i1.AuthSuccess>(
    'emailIdp',
    'finishRegistration',
    {
      'registrationToken': registrationToken,
      'password': password,
    },
  );

  /// Requests a password reset for [email].
  ///
  /// If the email address is registered, an email with reset instructions will
  /// be send out. If the email is unknown, this method will have no effect.
  ///
  /// Always returns a password reset request ID, which can be used to complete
  /// the reset. If the email is not registered, the returned ID will not be
  /// valid.
  ///
  /// Throws an [EmailAccountPasswordResetException] in case of errors, with reason:
  /// - [EmailAccountPasswordResetExceptionReason.tooManyAttempts] if the user has
  ///   made too many attempts trying to request a password reset.
  ///
  @override
  _i3.Future<_i2.UuidValue> startPasswordReset({required String email}) =>
      caller.callServerEndpoint<_i2.UuidValue>(
        'emailIdp',
        'startPasswordReset',
        {'email': email},
      );

  /// Verifies a password reset code and returns a finishPasswordResetToken
  /// that can be used to finish the password reset.
  ///
  /// Throws an [EmailAccountPasswordResetException] in case of errors, with reason:
  /// - [EmailAccountPasswordResetExceptionReason.expired] if the password reset
  ///   request has already expired.
  /// - [EmailAccountPasswordResetExceptionReason.tooManyAttempts] if the user has
  ///   made too many attempts trying to verify the password reset.
  /// - [EmailAccountPasswordResetExceptionReason.invalid] if no request exists
  ///   for the given [passwordResetRequestId] or [verificationCode] is invalid.
  ///
  /// If multiple steps are required to complete the password reset, this endpoint
  /// should be overridden to return credentials for the next step instead
  /// of the credentials for setting the password.
  @override
  _i3.Future<String> verifyPasswordResetCode({
    required _i2.UuidValue passwordResetRequestId,
    required String verificationCode,
  }) => caller.callServerEndpoint<String>(
    'emailIdp',
    'verifyPasswordResetCode',
    {
      'passwordResetRequestId': passwordResetRequestId,
      'verificationCode': verificationCode,
    },
  );

  /// Completes a password reset request by setting a new password.
  ///
  /// The [verificationCode] returned from [verifyPasswordResetCode] is used to
  /// validate the password reset request.
  ///
  /// Throws an [EmailAccountPasswordResetException] in case of errors, with reason:
  /// - [EmailAccountPasswordResetExceptionReason.expired] if the password reset
  ///   request has already expired.
  /// - [EmailAccountPasswordResetExceptionReason.policyViolation] if the new
  ///   password does not comply with the password policy.
  /// - [EmailAccountPasswordResetExceptionReason.invalid] if no request exists
  ///   for the given [passwordResetRequestId] or [verificationCode] is invalid.
  ///
  /// Throws an [AuthUserBlockedException] if the auth user is blocked.
  @override
  _i3.Future<void> finishPasswordReset({
    required String finishPasswordResetToken,
    required String newPassword,
  }) => caller.callServerEndpoint<void>(
    'emailIdp',
    'finishPasswordReset',
    {
      'finishPasswordResetToken': finishPasswordResetToken,
      'newPassword': newPassword,
    },
  );
}

/// Endpoint for retrieving public server configuration.
/// All methods are public - no authentication required.
/// {@category Endpoint}
class EndpointConfig extends _i2.EndpointRef {
  EndpointConfig(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'config';

  /// Returns public server configuration for client apps.
  ///
  /// This endpoint is unauthenticated so clients can check
  /// feature availability before login.
  _i3.Future<_i5.PublicConfig> getPublicConfig() =>
      caller.callServerEndpoint<_i5.PublicConfig>(
        'config',
        'getPublicConfig',
        {},
      );
}

/// Admin endpoint for managing questions.
/// All methods require authentication.
/// {@category Endpoint}
class EndpointQuestionAdmin extends _i2.EndpointRef {
  EndpointQuestionAdmin(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'questionAdmin';

  /// Add a question to a survey.
  _i3.Future<_i6.Question> create(_i6.Question question) =>
      caller.callServerEndpoint<_i6.Question>(
        'questionAdmin',
        'create',
        {'question': question},
      );

  /// Update a question.
  _i3.Future<_i6.Question> update(_i6.Question question) =>
      caller.callServerEndpoint<_i6.Question>(
        'questionAdmin',
        'update',
        {'question': question},
      );

  /// Delete a question and its options.
  _i3.Future<bool> delete(int questionId) => caller.callServerEndpoint<bool>(
    'questionAdmin',
    'delete',
    {'questionId': questionId},
  );

  /// Reorder questions within a survey.
  /// Pass the question IDs in the desired order.
  _i3.Future<List<_i6.Question>> reorder(
    int surveyId,
    List<int> questionIds,
  ) => caller.callServerEndpoint<List<_i6.Question>>(
    'questionAdmin',
    'reorder',
    {
      'surveyId': surveyId,
      'questionIds': questionIds,
    },
  );

  /// Get all questions for a survey.
  _i3.Future<List<_i6.Question>> getForSurvey(int surveyId) =>
      caller.callServerEndpoint<List<_i6.Question>>(
        'questionAdmin',
        'getForSurvey',
        {'surveyId': surveyId},
      );

  /// Get a question by ID.
  _i3.Future<_i6.Question?> getById(int questionId) =>
      caller.callServerEndpoint<_i6.Question?>(
        'questionAdmin',
        'getById',
        {'questionId': questionId},
      );

  /// Get all options for a question.
  _i3.Future<List<_i7.QuestionOption>> getOptionsForQuestion(int questionId) =>
      caller.callServerEndpoint<List<_i7.QuestionOption>>(
        'questionAdmin',
        'getOptionsForQuestion',
        {'questionId': questionId},
      );
}

/// Admin endpoint for managing question options.
/// All methods require authentication.
/// {@category Endpoint}
class EndpointQuestionOptionAdmin extends _i2.EndpointRef {
  EndpointQuestionOptionAdmin(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'questionOptionAdmin';

  /// Add an option to a question.
  _i3.Future<_i7.QuestionOption> create(_i7.QuestionOption option) =>
      caller.callServerEndpoint<_i7.QuestionOption>(
        'questionOptionAdmin',
        'create',
        {'option': option},
      );

  /// Update an option.
  _i3.Future<_i7.QuestionOption> update(_i7.QuestionOption option) =>
      caller.callServerEndpoint<_i7.QuestionOption>(
        'questionOptionAdmin',
        'update',
        {'option': option},
      );

  /// Delete an option.
  _i3.Future<bool> delete(int optionId) => caller.callServerEndpoint<bool>(
    'questionOptionAdmin',
    'delete',
    {'optionId': optionId},
  );

  /// Reorder options within a question.
  /// Pass the option IDs in the desired order.
  _i3.Future<List<_i7.QuestionOption>> reorder(
    int questionId,
    List<int> optionIds,
  ) => caller.callServerEndpoint<List<_i7.QuestionOption>>(
    'questionOptionAdmin',
    'reorder',
    {
      'questionId': questionId,
      'optionIds': optionIds,
    },
  );

  /// Get an option by ID.
  _i3.Future<_i7.QuestionOption?> getById(int optionId) =>
      caller.callServerEndpoint<_i7.QuestionOption?>(
        'questionOptionAdmin',
        'getById',
        {'optionId': optionId},
      );
}

/// Admin endpoint for viewing and analyzing survey responses.
/// All methods require authentication.
/// {@category Endpoint}
class EndpointResponseAnalytics extends _i2.EndpointRef {
  EndpointResponseAnalytics(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'responseAnalytics';

  /// Get all responses for a survey with pagination.
  _i3.Future<List<_i8.SurveyResponse>> getResponses(
    int surveyId, {
    int? limit,
    int? offset,
  }) => caller.callServerEndpoint<List<_i8.SurveyResponse>>(
    'responseAnalytics',
    'getResponses',
    {
      'surveyId': surveyId,
      'limit': limit,
      'offset': offset,
    },
  );

  /// Get response count for a survey.
  _i3.Future<int> getResponseCount(int surveyId) =>
      caller.callServerEndpoint<int>(
        'responseAnalytics',
        'getResponseCount',
        {'surveyId': surveyId},
      );

  /// Get all answers for a response.
  _i3.Future<List<_i9.Answer>> getAnswersForResponse(int responseId) =>
      caller.callServerEndpoint<List<_i9.Answer>>(
        'responseAnalytics',
        'getAnswersForResponse',
        {'responseId': responseId},
      );

  /// Get aggregated results for a survey.
  _i3.Future<_i10.SurveyResults> getAggregatedResults(int surveyId) =>
      caller.callServerEndpoint<_i10.SurveyResults>(
        'responseAnalytics',
        'getAggregatedResults',
        {'surveyId': surveyId},
      );

  /// Get response trends over time (daily counts for the last N days).
  _i3.Future<Map<String, int>> getResponseTrends(
    int surveyId, {
    required int days,
  }) => caller.callServerEndpoint<Map<String, int>>(
    'responseAnalytics',
    'getResponseTrends',
    {
      'surveyId': surveyId,
      'days': days,
    },
  );

  /// Delete a specific response.
  _i3.Future<bool> deleteResponse(int responseId) =>
      caller.callServerEndpoint<bool>(
        'responseAnalytics',
        'deleteResponse',
        {'responseId': responseId},
      );
}

/// Admin endpoint for managing surveys.
/// All methods require authentication.
/// {@category Endpoint}
class EndpointSurveyAdmin extends _i2.EndpointRef {
  EndpointSurveyAdmin(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'surveyAdmin';

  /// Create a new survey.
  _i3.Future<_i11.Survey> create(_i11.Survey survey) =>
      caller.callServerEndpoint<_i11.Survey>(
        'surveyAdmin',
        'create',
        {'survey': survey},
      );

  /// Update an existing survey.
  _i3.Future<_i11.Survey> update(_i11.Survey survey) =>
      caller.callServerEndpoint<_i11.Survey>(
        'surveyAdmin',
        'update',
        {'survey': survey},
      );

  /// Delete a survey and all related data.
  _i3.Future<bool> delete(int surveyId) => caller.callServerEndpoint<bool>(
    'surveyAdmin',
    'delete',
    {'surveyId': surveyId},
  );

  /// List all surveys for the current admin.
  _i3.Future<List<_i11.Survey>> list() =>
      caller.callServerEndpoint<List<_i11.Survey>>(
        'surveyAdmin',
        'list',
        {},
      );

  /// Get a survey by ID.
  _i3.Future<_i11.Survey?> getById(int surveyId) =>
      caller.callServerEndpoint<_i11.Survey?>(
        'surveyAdmin',
        'getById',
        {'surveyId': surveyId},
      );

  /// Publish a survey.
  _i3.Future<_i11.Survey> publish(int surveyId) =>
      caller.callServerEndpoint<_i11.Survey>(
        'surveyAdmin',
        'publish',
        {'surveyId': surveyId},
      );

  /// Close a survey (stop accepting responses).
  _i3.Future<_i11.Survey> close(int surveyId) =>
      caller.callServerEndpoint<_i11.Survey>(
        'surveyAdmin',
        'close',
        {'surveyId': surveyId},
      );

  /// Reopen a closed survey.
  _i3.Future<_i11.Survey> reopen(int surveyId) =>
      caller.callServerEndpoint<_i11.Survey>(
        'surveyAdmin',
        'reopen',
        {'surveyId': surveyId},
      );
}

/// Public endpoint for accessing surveys and submitting responses.
/// No authentication required for anonymous surveys.
/// {@category Endpoint}
class EndpointSurvey extends _i2.EndpointRef {
  EndpointSurvey(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'survey';

  /// Get a published survey by its slug.
  /// Returns null if the survey doesn't exist or is not published.
  _i3.Future<_i11.Survey?> getBySlug(String slug) =>
      caller.callServerEndpoint<_i11.Survey?>(
        'survey',
        'getBySlug',
        {'slug': slug},
      );

  /// Submit a response to a survey.
  /// For authenticated surveys, the user must be logged in.
  /// For anonymous surveys, an anonymousId can be provided for tracking.
  _i3.Future<_i8.SurveyResponse> submitResponse({
    required int surveyId,
    required List<_i9.Answer> answers,
    String? anonymousId,
  }) => caller.callServerEndpoint<_i8.SurveyResponse>(
    'survey',
    'submitResponse',
    {
      'surveyId': surveyId,
      'answers': answers,
      'anonymousId': anonymousId,
    },
  );
}

/// Admin endpoint for managing users.
/// Most methods require authentication, except for first user registration.
/// {@category Endpoint}
class EndpointUserAdmin extends _i2.EndpointRef {
  EndpointUserAdmin(_i2.EndpointCaller caller) : super(caller);

  @override
  String get name => 'userAdmin';

  /// Check if this is the first user (no users exist yet).
  /// This endpoint is public - no authentication required.
  _i3.Future<bool> isFirstUser() => caller.callServerEndpoint<bool>(
    'userAdmin',
    'isFirstUser',
    {},
  );

  /// Register the first admin user.
  /// Only works if no users exist yet.
  _i3.Future<_i1.AuthSuccess> registerFirstUser({
    required String email,
    required String password,
  }) => caller.callServerEndpoint<_i1.AuthSuccess>(
    'userAdmin',
    'registerFirstUser',
    {
      'email': email,
      'password': password,
    },
  );

  /// Get all users. Requires admin scope.
  _i3.Future<List<_i12.AuthUserInfo>> listUsers() =>
      caller.callServerEndpoint<List<_i12.AuthUserInfo>>(
        'userAdmin',
        'listUsers',
        {},
      );

  /// Create a new user. Requires admin scope.
  _i3.Future<_i12.AuthUserInfo> createUser({
    required String email,
    required String password,
    required List<String> scopes,
  }) => caller.callServerEndpoint<_i12.AuthUserInfo>(
    'userAdmin',
    'createUser',
    {
      'email': email,
      'password': password,
      'scopes': scopes,
    },
  );

  /// Delete a user. Requires admin scope.
  /// Returns true if the deleted user was the current user (self-deletion).
  _i3.Future<bool> deleteUser(_i2.UuidValue userId) =>
      caller.callServerEndpoint<bool>(
        'userAdmin',
        'deleteUser',
        {'userId': userId},
      );

  /// Toggle user blocked status. Requires admin scope.
  _i3.Future<bool> toggleUserBlocked(_i2.UuidValue userId) =>
      caller.callServerEndpoint<bool>(
        'userAdmin',
        'toggleUserBlocked',
        {'userId': userId},
      );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_idp = _i4.Caller(client);
    serverpod_auth_core = _i1.Caller(client);
  }

  late final _i4.Caller serverpod_auth_idp;

  late final _i1.Caller serverpod_auth_core;
}

class Client extends _i2.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    @Deprecated(
      'Use authKeyProvider instead. This will be removed in future releases.',
    )
    super.authenticationKeyManager,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _i2.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_i2.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
  }) : super(
         host,
         _i13.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
       ) {
    refreshJwtTokens = EndpointRefreshJwtTokens(this);
    emailIdp = EndpointEmailIdp(this);
    config = EndpointConfig(this);
    questionAdmin = EndpointQuestionAdmin(this);
    questionOptionAdmin = EndpointQuestionOptionAdmin(this);
    responseAnalytics = EndpointResponseAnalytics(this);
    surveyAdmin = EndpointSurveyAdmin(this);
    survey = EndpointSurvey(this);
    userAdmin = EndpointUserAdmin(this);
    modules = Modules(this);
  }

  late final EndpointRefreshJwtTokens refreshJwtTokens;

  late final EndpointEmailIdp emailIdp;

  late final EndpointConfig config;

  late final EndpointQuestionAdmin questionAdmin;

  late final EndpointQuestionOptionAdmin questionOptionAdmin;

  late final EndpointResponseAnalytics responseAnalytics;

  late final EndpointSurveyAdmin surveyAdmin;

  late final EndpointSurvey survey;

  late final EndpointUserAdmin userAdmin;

  late final Modules modules;

  @override
  Map<String, _i2.EndpointRef> get endpointRefLookup => {
    'refreshJwtTokens': refreshJwtTokens,
    'emailIdp': emailIdp,
    'config': config,
    'questionAdmin': questionAdmin,
    'questionOptionAdmin': questionOptionAdmin,
    'responseAnalytics': responseAnalytics,
    'surveyAdmin': surveyAdmin,
    'survey': survey,
    'userAdmin': userAdmin,
  };

  @override
  Map<String, _i2.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
