import 'dart:convert';
import 'dart:io';

void main() {
  final outputs = <File>[];
  _generate(
    inputDirectory: Directory('admin_dashboard/l10n/admin'),
    output: File(
      'admin_dashboard/lib/src/core/localization/admin_messages.g.dart',
    ),
    declaration: 'adminLocalizedValues',
    header: '// Generated by tool/generate_localizations.dart. Do not edit.\n',
    outputs: outputs,
  );
  _generate(
    inputDirectory: Directory('client/l10n/form_content'),
    output: File('client/lib/src/models/survey_messages.g.dart'),
    declaration: 'formContentLocalizedValues',
    header:
        '// Generated by tool/generate_localizations.dart. Do not edit.\n'
        "part of form_concierge_client;\n",
    outputs: outputs,
  );
  final result = Process.runSync('dart', [
    'format',
    ...outputs.map((file) => file.path),
  ]);
  if (result.exitCode != 0) {
    stderr.write(result.stderr);
    exitCode = result.exitCode;
  }
}

void _generate({
  required Directory inputDirectory,
  required File output,
  required String declaration,
  required String header,
  required List<File> outputs,
}) {
  final translations = <String, Map<String, String>>{};
  final files =
      inputDirectory
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.arb'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  for (final file in files) {
    final document =
        jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    final locale = (document.remove('@@locale') as String).replaceAll('_', '-');
    document.removeWhere((key, _) => key.startsWith('@'));
    translations[locale] = document.map(
      (key, value) => MapEntry(key, value as String),
    );
  }

  _validateTranslations(inputDirectory.path, translations);

  final buffer = StringBuffer(header)
    ..writeln()
    ..writeln('const $declaration = <String, Map<String, String>>{');
  for (final locale in translations.keys) {
    buffer.writeln('  ${jsonEncode(locale)}: <String, String>{');
    for (final entry in translations[locale]!.entries) {
      buffer.writeln(
        '    ${jsonEncode(entry.key)}: ${jsonEncode(entry.value)},',
      );
    }
    buffer.writeln('  },');
  }
  buffer.writeln('};');
  output.writeAsStringSync(buffer.toString());
  outputs.add(output);
}

void _validateTranslations(
  String source,
  Map<String, Map<String, String>> translations,
) {
  final english = translations['en'];
  if (english == null) throw FormatException('$source has no English ARB');
  final placeholderPattern = RegExp(r'\{[^}]+\}');
  for (final localeEntry in translations.entries) {
    final missing = english.keys.toSet().difference(
      localeEntry.value.keys.toSet(),
    );
    final extra = localeEntry.value.keys.toSet().difference(
      english.keys.toSet(),
    );
    if (missing.isNotEmpty || extra.isNotEmpty) {
      throw FormatException(
        '$source/${localeEntry.key}: missing ${missing.toList()}, '
        'extra ${extra.toList()}',
      );
    }
    for (final key in english.keys) {
      final expected = placeholderPattern
          .allMatches(english[key]!)
          .map((match) => match[0])
          .toSet();
      final actual = placeholderPattern
          .allMatches(localeEntry.value[key]!)
          .map((match) => match[0])
          .toSet();
      if (expected.length != actual.length || !expected.containsAll(actual)) {
        throw FormatException(
          '$source/${localeEntry.key}: placeholders differ for "$key": '
          '$expected != $actual',
        );
      }
    }
  }
}
